-- ═══════════════════════════════════════════════════════════════
-- MAINTENANCE (role_tag = 'maintenance')
-- Aircraft maintenance engineers and technicians
-- 68 questions
-- ═══════════════════════════════════════════════════════════════

INSERT INTO questions (section, type, content, correct_answer, cefr_level, difficulty, competency_tag, aircraft_context, role_tag, active, is_latest, version_number) VALUES
-- Grammar (20)
('grammar','multiple_choice','The technician _____ the landing gear before the aircraft departed.\nA) inspect\nB) inspected\nC) inspecting\nD) has inspect','B','A2','easy','tense_usage','landing_gear','maintenance',true,true,1),
('grammar','multiple_choice','All maintenance tasks _____ be completed before the aircraft is released.\nA) must\nB) can\nC) might\nD) would','A','B1','easy','structural_accuracy','general','maintenance',true,true,1),
('grammar','multiple_choice','The engine oil _____ changed every 500 flight hours.\nA) is\nB) are\nC) were\nD) been','A','A2','easy','passive_voice','engine','maintenance',true,true,1),
('grammar','multiple_choice','If the hydraulic pressure _____ too low, the warning light will illuminate.\nA) is\nB) will be\nC) was\nD) has been','A','B1','medium','conditional_forms','hydraulic','maintenance',true,true,1),
('grammar','multiple_choice','The mechanic reported that the brake pads _____ worn beyond limits.\nA) is\nB) was\nC) were\nD) are','C','B1','medium','tense_usage','landing_gear','maintenance',true,true,1),
('grammar','multiple_choice','Please ensure that all tools _____ returned to the toolbox after use.\nA) is\nB) are\nC) was\nD) has been','B','A2','easy','passive_voice','general','maintenance',true,true,1),
('grammar','multiple_choice','The aircraft _____ in the hangar since yesterday morning.\nA) is\nB) was\nC) has been\nD) had','C','B1','medium','tense_usage','general','maintenance',true,true,1),
('grammar','multiple_choice','A torque wrench is used _____ tightening bolts to a specific value.\nA) to\nB) for\nC) with\nD) by','B','A2','easy','phraseology_grammar','general','maintenance',true,true,1),
('grammar','fill_blank','Complete: The corrosion must be treated _____ (immediate) to prevent further damage.','immediately','B1','medium','structural_accuracy','airframe','maintenance',true,true,1),
('grammar','multiple_choice','The work order states that the component _____ be replaced within 48 hours.\nA) shall\nB) will\nC) can\nD) may','A','B1','medium','phraseology_grammar','general','maintenance',true,true,1),
('grammar','multiple_choice','After _____ the inspection, the engineer signed the release certificate.\nA) complete\nB) completing\nC) completed\nD) to complete','B','B1','medium','structural_accuracy','general','maintenance',true,true,1),
('grammar','multiple_choice','The safety wire _____ correctly installed on the drain plug.\nA) is not\nB) does not\nC) not\nD) no','A','A2','easy','passive_voice','general','maintenance',true,true,1),
('grammar','fill_blank','Complete: The borescope inspection was performed _____ (careful) on all turbine blades.','carefully','A2','easy','structural_accuracy','engine','maintenance',true,true,1),
('grammar','multiple_choice','The corrosion was found _____ the leading edge of the wing.\nA) in\nB) on\nC) at\nD) by','B','A2','easy','phraseology_grammar','airframe','maintenance',true,true,1),
('grammar','multiple_choice','The technician asked his supervisor _____ he should use a different sealant.\nA) what\nB) which\nC) whether\nD) how','C','B1','medium','structural_accuracy','general','maintenance',true,true,1),
('grammar','multiple_choice','We _____ replace the gasket before the engine can be tested.\nA) need to\nB) need\nC) needs to\nD) needing','A','A2','easy','structural_accuracy','engine','maintenance',true,true,1),
('grammar','multiple_choice','The NDT results showed that the crack _____ propagated further than expected.\nA) has\nB) had\nC) have\nD) having','B','B2','hard','tense_usage','airframe','maintenance',true,true,1),
('grammar','multiple_choice','_____ the repair is completed, a functional test must be performed.\nA) Once\nB) While\nC) During\nD) Since','A','B1','medium','structural_accuracy','general','maintenance',true,true,1),
('grammar','fill_blank','Complete: The hydraulic fluid level was _____ (danger) low.','dangerously','B1','medium','structural_accuracy','hydraulic','maintenance',true,true,1),
('grammar','multiple_choice','Each component _____ have a valid serviceable tag before installation.\nA) must\nB) can\nC) might\nD) could','A','B1','medium','phraseology_grammar','general','maintenance',true,true,1),

-- Reading (10)
('reading','multiple_choice','Read the maintenance instruction:\n\n"CAUTION: Before removing the fuel filter, ensure the fuel supply valve is in the CLOSED position. Failure to close the valve may result in fuel spillage and fire hazard. Use only approved containers for residual fuel."\n\nWhat must be done FIRST?\nA) Collect residual fuel\nB) Close the fuel supply valve\nC) Check for fire hazards\nD) Open the filter housing','B','A2','easy','technical_manual','fuel_system','maintenance',true,true,1),
('reading','multiple_choice','Read the work order:\n\n"Task: Replace left main gear tire. Ref: AMM 32-45-11. Priority: Routine. Tire pressure at 145 psi (min: 150 psi). New tire P/N: GY-2847-3. Torque: 300 in-lbs per AMM."\n\nWhy must the tire be replaced?\nA) Flight hour limit reached\nB) Pressure below minimum\nC) Tread too shallow\nD) Wheel bolts damaged','B','B1','medium','sop_comprehension','landing_gear','maintenance',true,true,1),
('reading','multiple_choice','Read the safety notice:\n\n"All personnel in fuel tank areas must wear anti-static clothing and use non-sparking tools. Mobile phones prohibited within 15m of open fuel tanks. Violations: immediate removal from work area."\n\nWhat is NOT allowed near fuel tanks?\nA) Anti-static clothing\nB) Non-sparking tools\nC) Mobile phones\nD) Safety goggles','C','A2','easy','safety_card_reading','fuel_system','maintenance',true,true,1),
('reading','multiple_choice','Read the AMM excerpt:\n\n"5.2 Lubrication: The nose gear steering mechanism shall be lubricated with MIL-G-81322 grease at intervals not exceeding 200 FH or 90 calendar days, whichever first. Apply through upper torque link fitting until fresh grease at lower seal."\n\nHow often must the nose gear be lubricated?\nA) Every 200 flights\nB) Every 200 FH or 90 days, whichever first\nC) Every 90 flights\nD) Only when grease appears','B','B1','medium','technical_manual','landing_gear','maintenance',true,true,1),
('reading','multiple_choice','Read the SRM (Structural Repair Manual) entry:\n\n"Allowable damage: Dents in fuselage skin not exceeding 0.5mm depth and 30mm diameter. Dents deeper than 0.5mm or within 25mm of a rivet line require engineering assessment. Scratches deeper than 0.1mm must be blended and treated with corrosion inhibitor."\n\nA dent is 0.8mm deep. What should be done?\nA) No action needed\nB) Engineering assessment required\nC) Apply corrosion inhibitor\nD) Blend the dent','B','B2','hard','technical_manual','airframe','maintenance',true,true,1),
('reading','multiple_choice','Read the tool calibration notice:\n\n"All torque wrenches used on critical flight-safety components must be calibrated every 6 months or after 5000 cycles of use, whichever occurs first. Out-of-calibration tools must not be used and should be tagged with a red UNSERVICEABLE label."\n\nWhat happens to out-of-calibration tools?\nA) They can still be used with caution\nB) They are tagged red and cannot be used\nC) They are discarded\nD) They are sent to the manufacturer','B','B1','medium','sop_comprehension','general','maintenance',true,true,1),
('reading','multiple_choice','Read the service bulletin:\n\n"SB-A320-57-1089: Inspect wing root fairing attachment bolts for corrosion. Applicability: All A320 aircraft with MSN below 5000. Compliance: Within next 2000 FH or 12 months. Action: Replace any bolt with visible corrosion, apply new sealant per AMM 51-70-11."\n\nWhich aircraft are affected?\nA) All A320s\nB) A320s with MSN below 5000\nC) Only new A320s\nD) A320neo only','B','B2','hard','technical_manual','airframe','maintenance',true,true,1),
('reading','multiple_choice','Read the shift log:\n\n"Night shift summary: TC-SUN — C-check Day 3, engine 1 borescope complete (no findings), landing gear overhaul in progress. TC-AIR — tire change completed Bay 5, awaiting QC inspection. TC-FLY — AOG, waiting for hydraulic pump (ETA tomorrow 0800)."\n\nWhich aircraft is AOG?\nA) TC-SUN\nB) TC-AIR\nC) TC-FLY\nD) All of them','C','B1','medium','sop_comprehension','general','maintenance',true,true,1),
('reading','multiple_choice','Read the hazardous materials guide:\n\n"SKYDROL hydraulic fluid: AVOID skin and eye contact. Wear nitrile gloves and safety goggles. If skin contact occurs, wash immediately with soap and water for 15 minutes. If swallowed, do NOT induce vomiting — seek medical attention immediately."\n\nWhat type of gloves should be worn?\nA) Latex gloves\nB) Nitrile gloves\nC) Cotton gloves\nD) No gloves needed','B','A2','easy','safety_card_reading','hydraulic','maintenance',true,true,1),
('reading','multiple_choice','Read the AD (Airworthiness Directive):\n\n"AD 2026-05-12: Mandatory inspection of fuel quantity indicating system wiring harness for chafing. Affected: B737-800 with line numbers 3500-4200. Compliance: Within 500 FH of effective date. Failure to comply results in aircraft grounding."\n\nWhat is the consequence of non-compliance?\nA) A warning letter\nB) The aircraft must be grounded\nC) A fine\nD) No consequence','B','B2','hard','technical_manual','fuel_system','maintenance',true,true,1),

-- Writing (8)
('writing','written_response','During a routine inspection of a B737, you found a 3cm crack on the left wing leading edge near the fuel vent. Write a maintenance log entry (at least 50 words) describing what you found, location, and recommended action.','Model answer should include aircraft type/reg, specific location, crack dimensions, findings, recommendation for NDT inspection and engineering assessment.','B1','medium','maintenance_log','airframe','maintenance',true,true,1),
('writing','written_response','You found tools left inside an engine cowling after maintenance — a serious FOD risk. Write an incident report (at least 50 words) describing what happened, where, and what you did.','Model answer should include factual description, tool details, location, removal, reporting to supervisor, tool inventory check.','A2','easy','incident_report','engine','maintenance',true,true,1),
('writing','written_response','Write an email to the parts department (at least 50 words) urgently requesting a replacement hydraulic actuator for an AOG aircraft. Include the aircraft registration, part number, and delivery urgency.','Model answer should include formal request, aircraft details, part specifics, AOG status, requested delivery time.','B1','medium','operational_message','hydraulic','maintenance',true,true,1),
('writing','written_response','A new apprentice joined your team. Write an email to your supervisor (at least 50 words) about the apprentice, planned tasks for the week, and pending safety training.','Model answer should include apprentice details, task assignments, training requirements, supervision plan.','B1','medium','operational_message','general','maintenance',true,true,1),
('writing','written_response','Write a defect report (at least 60 words) for an intermittent autopilot disconnect that occurred 3 times during the last 10 flights. Include the system affected, frequency, and your troubleshooting recommendation.','Model answer should include system ID, frequency of occurrence, flight conditions, possible causes, recommended troubleshooting steps.','B2','hard','technical_description','general','maintenance',true,true,1),
('writing','written_response','You completed an engine oil change and subsequent ground run. Write the technical log entry (at least 50 words) including oil type, quantity, and test results.','Model answer should include engine position, oil spec, quantity added, ground run parameters, results satisfactory.','B1','medium','maintenance_log','engine','maintenance',true,true,1),
('writing','written_response','Write a safety observation report (at least 50 words) about inadequate lighting in the wheel bay area that makes inspection difficult and potentially dangerous during night shifts.','Model answer should include specific location, safety concern, impact on inspection quality, recommendation for additional lighting.','A2','easy','safety_report','general','maintenance',true,true,1),
('writing','written_response','Write a brief procedure description (at least 60 words) explaining how to perform a brake wear pin check on a main landing gear wheel. Include safety precautions.','Model answer should include chocking aircraft, safety procedures, visual inspection method, wear limits, documentation.','B2','medium','technical_description','landing_gear','maintenance',true,true,1),

-- Speaking (8)
('speaking','audio_response','Describe the steps for a daily pre-flight visual inspection. Talk about at least 3 areas and why each is important.\n\nSpeak for at least 30 seconds.','Expected: Airframe check, tires, fluids, control surfaces, leaks, fasteners. Clear structure.','B1','medium','oral_briefing','general','maintenance',true,true,1),
('speaking','audio_response','Your supervisor asks: "What safety precautions do you take near fuel systems?" Respond with at least 3 precautions.\n\nSpeak for at least 30 seconds.','Expected: Anti-static clothing, non-sparking tools, no electronics, fire extinguisher, ventilation.','A2','easy','ground_communication','fuel_system','maintenance',true,true,1),
('speaking','audio_response','Roleplay: Call the parts department to order a replacement brake assembly for an A320. Explain what you need, why, and ask about availability.\n\nSpeak for at least 30 seconds.','Expected: Self-identification, aircraft details, part needed, reason, delivery question.','B1','medium','ground_communication','landing_gear','maintenance',true,true,1),
('speaking','audio_response','Explain what FOD means and why it is dangerous in aviation. Give one prevention example.\n\nSpeak for at least 30 seconds.','Expected: FOD definition, examples of damage, prevention measures (tool control, clean areas, FOD walks).','A2','easy','oral_briefing','general','maintenance',true,true,1),
('speaking','audio_response','You are handing over to the night shift. Brief them on: what you completed today, what is pending, and any safety concerns.\n\nSpeak for at least 45 seconds.','Expected: Structured handover, completed tasks, pending work, parts status, safety notes, AOG status.','B1','medium','crew_coordination','general','maintenance',true,true,1),
('speaking','audio_response','Describe the process of performing a borescope inspection on a turbine engine. What are you looking for?\n\nSpeak for at least 40 seconds.','Expected: Equipment setup, inspection areas, common findings (cracks, erosion, FOD damage), documentation.','B2','hard','technical_description','engine','maintenance',true,true,1),
('speaking','audio_response','Roleplay: A pilot calls you on the intercom reporting a strange vibration during engine start. Ask diagnostic questions and explain what you will check.\n\nSpeak for at least 40 seconds.','Expected: Clarifying questions, systematic approach, possible causes, inspection plan.','B2','medium','ground_communication','engine','maintenance',true,true,1),
('speaking','audio_response','Explain to a new team member the importance of the "Duplicate Inspection" procedure. When is it required and why?\n\nSpeak for at least 30 seconds.','Expected: Definition, when required (flight controls, engines), two-person verification, safety purpose.','B1','medium','oral_briefing','general','maintenance',true,true,1),

-- Listening (12)
('listening','multiple_choice','[AUDIO] "Maintenance Control, this is Hangar 3. We have completed the engine oil change on TC-FLY. Oil quantity 12 quarts. Ready for engine run-up test."\n\nWhat was completed?\nA) Tire change\nB) Engine oil change\nC) Fuel system check\nD) Hydraulic test','B','A2','easy','ground_ops_radio','engine','maintenance',true,true,1),
('listening','multiple_choice','[AUDIO] "Attention all personnel. Thunderstorm warning — all outdoor maintenance suspended immediately. Secure aircraft on ramp with additional tie-downs. Move to indoor locations. Resume after all-clear."\n\nWhat must happen to ramp aircraft?\nA) Move to hangar\nB) Secure with extra tie-downs\nC) Fuel immediately\nD) Nothing','B','A2','easy','emergency_broadcast','general','maintenance',true,true,1),
('listening','multiple_choice','[AUDIO] "Night shift status: TC-SUN Bay 2 needs left main gear tire — parts staged. TC-AIR Bay 5 waiting for hydraulic pump from stores, ETA midnight. TC-FLY in paint shop — not our responsibility tonight."\n\nWhich aircraft awaits a stores part?\nA) TC-SUN\nB) TC-AIR\nC) TC-FLY\nD) All of them','B','B1','medium','cockpit_communication','general','maintenance',true,true,1),
('listening','multiple_choice','[AUDIO] "Ground, Maintenance Tug 7. Requesting tow permission — TC-JET from Gate 14 to Hangar 2 via Taxiway Alpha. Wing walkers in position."\n\nWhere is the aircraft going?\nA) Gate 14\nB) Hangar 2\nC) Taxiway Alpha\nD) The runway','B','A2','easy','ground_ops_radio','general','maintenance',true,true,1),
('listening','multiple_choice','[AUDIO] "Team, we have an AOG on TC-BIRD. Right engine starter motor failed. Airline needs it by 0600 tomorrow. I need two experienced techs on this immediately."\n\nWhat does AOG mean here?\nA) Aircraft On Ground — cannot fly until repaired\nB) Aircraft Operating Good\nC) Arrival On Gate\nD) All Operations Go','A','B1','medium','cockpit_communication','engine','maintenance',true,true,1),
('listening','multiple_choice','[AUDIO] "The replacement hydraulic actuator for TC-SUN arrived from Istanbul. P/N HYD-4421-B. Currently in Receiving — needs Quality inspection before install. ETA release: 1400 local."\n\nWhen will the part be available?\nA) Immediately\nB) After quality inspection, around 1400\nC) Tomorrow morning\nD) It hasn''t arrived','B','B1','medium','ground_ops_radio','hydraulic','maintenance',true,true,1),
('listening','multiple_choice','[AUDIO] "When you lock-wire a bolt, ensure the wire pulls in the tightening direction. Use 0.032-inch wire for standard applications. Minimum 6 twists per inch. Never reuse lock wire."\n\nMinimum twists per inch?\nA) 3\nB) 4\nC) 6\nD) 8','C','B1','medium','ground_ops_radio','general','maintenance',true,true,1),
('listening','multiple_choice','[AUDIO] "Calibration lab closed this Friday for upgrades. All torque wrenches due this week must be submitted by Thursday end of shift. Late submissions scheduled next week."\n\nDeadline for calibration submissions?\nA) Friday morning\nB) Thursday end of shift\nC) Next Monday\nD) Immediately','B','A2','easy','ground_ops_radio','general','maintenance',true,true,1),
('listening','multiple_choice','[AUDIO] "Warning: The aircraft at Stand 9 still has live electrical power connected. Do NOT disconnect the external power unit until the avionics team completes their software update. Estimated completion: 45 minutes."\n\nWhat must NOT be done?\nA) Board the aircraft\nB) Disconnect external power\nC) Start the engines\nD) Open the cargo doors','B','B1','medium','ground_ops_radio','general','maintenance',true,true,1),
('listening','multiple_choice','[AUDIO] "Quality inspector to Hangar 4: I have completed the buy-back inspection on the left engine following the compressor blade replacement. All torque values confirmed. Documentation is in order. The engine is released to service. You may proceed with cowl closure."\n\nWhat can the team do now?\nA) Replace another blade\nB) Close the engine cowlings\nC) Wait for another inspection\nD) Order more parts','B','B1','medium','ground_ops_radio','engine','maintenance',true,true,1),
('listening','multiple_choice','[AUDIO] "Attention maintenance: runway FOD check commencing in 10 minutes. All personnel and vehicles must vacate Runway 36L and associated taxiways Alpha and Bravo. Confirm when your area is clear on this frequency."\n\nWhat is about to happen?\nA) Aircraft landing\nB) Runway FOD inspection\nC) Fire drill\nD) Runway painting','B','A2','easy','ground_ops_radio','general','maintenance',true,true,1),
('listening','multiple_choice','[AUDIO] "The NDT technician reports that the ultrasonic inspection of the wing spar at Station 245 shows an indication of 4mm — this exceeds the allowable limit of 2.5mm per SRM. Engineering has been notified. Do not reassemble until disposition received."\n\nWhat must happen before reassembly?\nA) Another NDT test\nB) Engineering disposition must be received\nC) The spar must be replaced\nD) Nothing — it is acceptable','B','B2','hard','ground_ops_radio','airframe','maintenance',true,true,1);


-- ═══════════════════════════════════════════════════════════════
-- GROUND STAFF (role_tag = 'ground_staff')
-- Ground operations, ramp agents, dispatchers
-- 68 questions
-- ═══════════════════════════════════════════════════════════════

INSERT INTO questions (section, type, content, correct_answer, cefr_level, difficulty, competency_tag, aircraft_context, role_tag, active, is_latest, version_number) VALUES
-- Grammar (20)
('grammar','multiple_choice','The baggage _____ loaded onto the aircraft by the ground crew.\nA) is\nB) was\nC) were\nD) been','B','A2','easy','passive_voice','general','ground_staff',true,true,1),
('grammar','multiple_choice','All ground vehicles _____ be driven at a maximum of 25 km/h on the ramp.\nA) must\nB) can\nC) might\nD) would','A','A2','easy','structural_accuracy','general','ground_staff',true,true,1),
('grammar','multiple_choice','If it _____ raining, we need waterproof covers for the baggage carts.\nA) starts\nB) will start\nC) started\nD) has start','A','B1','medium','conditional_forms','general','ground_staff',true,true,1),
('grammar','multiple_choice','The aircraft _____ to Gate 15 after landing.\nA) was directed\nB) directed\nC) directing\nD) has direct','A','A2','easy','passive_voice','general','ground_staff',true,true,1),
('grammar','multiple_choice','Neither the tug driver _____ the marshaller saw the obstacle.\nA) or\nB) nor\nC) and\nD) but','B','B1','medium','structural_accuracy','general','ground_staff',true,true,1),
('grammar','fill_blank','Complete: The cargo must be handled _____ (care) to avoid damage.','carefully','A2','easy','structural_accuracy','general','ground_staff',true,true,1),
('grammar','multiple_choice','We have been waiting for the fuel truck _____ 30 minutes.\nA) since\nB) for\nC) during\nD) from','B','A2','easy','tense_usage','general','ground_staff',true,true,1),
('grammar','multiple_choice','The weight and balance sheet _____ completed before departure.\nA) must be\nB) must\nC) has\nD) should','A','B1','medium','passive_voice','general','ground_staff',true,true,1),
('grammar','multiple_choice','_____ the pushback tractor arrives, we cannot move the aircraft.\nA) Until\nB) While\nC) During\nD) Although','A','B1','medium','structural_accuracy','general','ground_staff',true,true,1),
('grammar','fill_blank','Complete: The marshaller signalled _____ (clear) for the aircraft to taxi forward.','clearly','A2','easy','structural_accuracy','general','ground_staff',true,true,1),
('grammar','multiple_choice','By the time the passengers arrived, we _____ already loaded all the baggage.\nA) had\nB) have\nC) has\nD) were','A','B2','medium','tense_usage','general','ground_staff',true,true,1),
('grammar','multiple_choice','High-visibility vests _____ be worn at all times on the ramp.\nA) must\nB) can\nC) might\nD) could','A','A2','easy','structural_accuracy','general','ground_staff',true,true,1),
('grammar','multiple_choice','The flight _____ delayed because the catering truck broke down.\nA) is\nB) was\nC) were\nD) been','B','A2','easy','tense_usage','general','ground_staff',true,true,1),
('grammar','multiple_choice','How _____ containers are we loading on this flight?\nA) many\nB) much\nC) some\nD) any','A','A2','easy','structural_accuracy','general','ground_staff',true,true,1),
('grammar','multiple_choice','The dispatcher confirmed that the load sheet _____ correct.\nA) is\nB) was\nC) were\nD) are','B','B1','medium','tense_usage','general','ground_staff',true,true,1),
('grammar','fill_blank','Complete: The de-icing was performed _____ (thorough) before takeoff.','thoroughly','B1','medium','structural_accuracy','general','ground_staff',true,true,1),
('grammar','multiple_choice','Each container _____ a maximum weight limit that must not be exceeded.\nA) has\nB) have\nC) having\nD) had','A','A2','easy','structural_accuracy','general','ground_staff',true,true,1),
('grammar','multiple_choice','The ground coordinator asked _____ the aircraft would arrive on time.\nA) that\nB) if\nC) what\nD) which','B','B1','medium','structural_accuracy','general','ground_staff',true,true,1),
('grammar','multiple_choice','We _____ just finished loading when the captain requested a weight change.\nA) had\nB) have\nC) has\nD) were','A','B1','medium','tense_usage','general','ground_staff',true,true,1),
('grammar','multiple_choice','Dangerous goods _____ be declared and properly labelled before loading.\nA) must\nB) can\nC) might\nD) should','A','B1','medium','phraseology_grammar','general','ground_staff',true,true,1),

-- Reading (10)
('reading','multiple_choice','Read the ramp safety sign:\n\n"WARNING: Jet blast zone — Stay clear of area behind running engines. Minimum safe distance: 60 metres for narrow-body, 100 metres for wide-body aircraft. Failure to maintain safe distance may result in serious injury or death."\n\nWhat is the safe distance from a wide-body engine?\nA) 30 metres\nB) 60 metres\nC) 100 metres\nD) 200 metres','C','A2','easy','safety_card_reading','general','ground_staff',true,true,1),
('reading','multiple_choice','Read the load instruction:\n\n"ULD Loading Sequence for TC-FLY (B737-800):\nForward hold: Positions 1-2: Bulk baggage. Position 3: Priority/fragile.\nAft hold: Positions 4-5: Standard baggage. Position 6: Mail/cargo.\nMaximum forward hold: 3,200 kg. Maximum aft hold: 4,500 kg."\n\nWhere should fragile items be loaded?\nA) Position 1\nB) Position 3\nC) Position 5\nD) Position 6','B','B1','medium','sop_comprehension','general','ground_staff',true,true,1),
('reading','multiple_choice','Read the dangerous goods label:\n\n"UN3481 — Lithium Ion Batteries packed with equipment. Class 9 Miscellaneous Dangerous Goods. Maximum: 5kg per package. Must be in original packaging. Keep upright. Do NOT load near heat sources or in pressurized cargo compartments above 25°C."\n\nWhat class of dangerous goods is this?\nA) Class 1 — Explosives\nB) Class 3 — Flammable liquid\nC) Class 9 — Miscellaneous\nD) Class 7 — Radioactive','C','B1','medium','technical_manual','general','ground_staff',true,true,1),
('reading','multiple_choice','Read the winter operations bulletin:\n\n"DE-ICING PROCEDURES: Type I fluid: heated — removes existing contamination. Type IV fluid: unheated — provides anti-icing protection. Holdover time for Type IV in moderate snow: 15-25 minutes. Aircraft must depart within holdover time or de-icing must be repeated."\n\nWhat happens if holdover time expires?\nA) Aircraft can still depart\nB) De-icing must be repeated\nC) Only Type I is reapplied\nD) The flight is cancelled','B','B1','medium','technical_manual','general','ground_staff',true,true,1),
('reading','multiple_choice','Read the turnaround schedule:\n\n"Target turnaround: 35 minutes\n0:00 — Aircraft on blocks, doors open\n0:05 — Catering, cleaning, fueling begin\n0:15 — Baggage offload complete\n0:20 — Boarding begins\n0:30 — Doors close, pushback clearance requested\n0:35 — Off blocks"\n\nWhen does boarding begin?\nA) At 0:05\nB) At 0:15\nC) At 0:20\nD) At 0:30','C','A2','easy','sop_comprehension','general','ground_staff',true,true,1),
('reading','multiple_choice','Read the vehicle safety rule:\n\n"All ramp vehicles must: 1) Have working lights and horn 2) Display valid inspection sticker 3) Not exceed 25 km/h (15 km/h near aircraft) 4) Give way to aircraft at all times 5) Not pass under aircraft wings or fuselage 6) Maintain 3-metre clearance from all aircraft."\n\nWhat is the speed limit near aircraft?\nA) 25 km/h\nB) 15 km/h\nC) 10 km/h\nD) 5 km/h','B','A2','easy','safety_card_reading','general','ground_staff',true,true,1),
('reading','multiple_choice','Read the load message:\n\n"LDM TC-FLY/18MAR\nPAX: 168/3/12 (M/F/CHD) + 2 INF\nBAG: 183 PCS / 2,745 KG\nCARGO: 450 KG (FWD), 320 KG (AFT)\nMAIL: 85 KG (AFT)\nTOTAL PAYLOAD: 14,320 KG\nMAX PAYLOAD: 16,200 KG"\n\nHow much additional payload capacity is available?\nA) 1,880 kg\nB) 2,745 kg\nC) 14,320 kg\nD) 450 kg','A','B2','hard','technical_manual','general','ground_staff',true,true,1),
('reading','multiple_choice','Read the FOD prevention policy:\n\n"All ground staff must perform a FOD walk of their assigned stand before and after each aircraft arrival/departure. Report findings on the daily FOD log. Any metal debris, loose bolts, or foreign objects must be collected immediately. FOD bins are located at each gate."\n\nWhen must FOD walks be performed?\nA) Only before arrivals\nB) Before and after each arrival/departure\nC) Once per day\nD) Only when requested','B','A2','easy','sop_comprehension','general','ground_staff',true,true,1),
('reading','multiple_choice','Read the communication protocol:\n\n"Headset Communication with Flight Deck:\n- Always identify yourself: ''Ground to flight deck''\n- Confirm pushback clearance: ''Cleared to push, facing [direction]''\n- Report brakes: ''Brakes set/released''\n- Disconnect: ''Cleared to start, disconnecting, have a safe flight''\n- NEVER walk under aircraft without headset connected"\n\nWhat must you say before disconnecting?\nA) Goodbye\nB) Cleared to start, disconnecting, have a safe flight\nC) Pushback complete\nD) Thank you','B','B1','medium','sop_comprehension','general','ground_staff',true,true,1),
('reading','multiple_choice','Read the weight restriction:\n\n"MANUAL HANDLING LIMITS:\n- One person: Maximum 23 kg\n- Two persons: Maximum 40 kg\n- Bags over 32 kg: Must use belt loader/mechanical lift\n- Oversized items (ski, wheelchair): Must be loaded last, removed first\nTeam lifting training must be completed annually."\n\nWhat is the max weight one person can lift?\nA) 15 kg\nB) 23 kg\nC) 32 kg\nD) 40 kg','B','A2','easy','safety_card_reading','general','ground_staff',true,true,1),

-- Writing (8)
('writing','written_response','A passenger''s suitcase was damaged during loading — the handle is broken and there is a large tear. Write a damage report (at least 50 words) including the flight, description of damage, and what you recommend.','Model answer should include flight number, bag tag, damage description, cause if known, compensation recommendation.','A2','easy','incident_report','general','ground_staff',true,true,1),
('writing','written_response','Write a shift handover note (at least 50 words) for the next ground crew shift. Include completed flights, pending tasks, equipment issues, and weather conditions.','Model answer should include completed turnarounds, pending departures, broken equipment, weather advisory.','B1','medium','operational_message','general','ground_staff',true,true,1),
('writing','written_response','A vehicle incident occurred on the ramp — a baggage tractor hit a cone and nearly struck an aircraft nose wheel. Write a safety report (at least 60 words) describing the incident and recommending preventive measures.','Model answer should include time, location, vehicle ID, driver, near-miss details, recommendations.','B1','medium','safety_report','general','ground_staff',true,true,1),
('writing','written_response','Write an email (at least 50 words) to the operations manager requesting new high-visibility vests for your team. The current ones are faded and no longer meet safety standards.','Model answer should include specific need, quantity, current condition, safety standard reference, urgency.','A2','easy','operational_message','general','ground_staff',true,true,1),
('writing','written_response','A flight has been overbooked and 5 passengers need to be offloaded. Write the announcement (at least 50 words) that would be made at the gate, offering compensation for volunteers.','Model answer should include professional tone, compensation offer, rebooking details, volunteer request.','B1','medium','cabin_announcement','general','ground_staff',true,true,1),
('writing','written_response','Write a brief procedure description (at least 50 words) explaining the correct pushback sequence from a terminal gate, including who communicates with whom.','Model answer should include chock removal, headset connection, clearance from tower, brake release, pushback direction.','B1','medium','technical_description','general','ground_staff',true,true,1),
('writing','written_response','You noticed that the de-icing fluid at your station has expired (past the batch expiry date on the label). Write a report (at least 50 words) to your supervisor about this issue.','Model answer should include fluid type, batch number, expiry date, location, safety concern, recommendation to replace.','B1','medium','safety_report','general','ground_staff',true,true,1),
('writing','written_response','Write a passenger complaint response (at least 60 words) for a traveler whose wheelchair was not at the aircraft door when they landed, causing them to wait 25 minutes on the jetbridge.','Model answer should include apology, acknowledge inconvenience, explain likely cause, corrective action, compensation if applicable.','B2','medium','passenger_complaint','general','ground_staff',true,true,1),

-- Speaking (8)
('speaking','audio_response','You are a marshaller guiding an aircraft to its parking stand. Describe the hand signals you would use and what each means.\n\nSpeak for at least 30 seconds.','Expected: Description of common signals — this way, slow down, stop, cut engines, chocks in. Clear explanation.','A2','easy','oral_briefing','general','ground_staff',true,true,1),
('speaking','audio_response','Roleplay: You are on the headset communicating with the flight deck during pushback. Walk through the complete pushback sequence from start to disconnect.\n\nSpeak for at least 40 seconds.','Expected: Ground to flight deck identification, clearance confirmed, brakes released, pushback direction, stop, cleared to start, disconnect.','B1','medium','ground_communication','general','ground_staff',true,true,1),
('speaking','audio_response','Explain the dangers of working near aircraft engines. What areas are dangerous and what precautions must be taken?\n\nSpeak for at least 30 seconds.','Expected: Intake danger zone, jet blast zone, distances, hearing protection, awareness of engine status.','A2','easy','oral_briefing','general','ground_staff',true,true,1),
('speaking','audio_response','A flight is delayed by 90 minutes and passengers at the gate are getting frustrated. How would you handle the situation? What would you say to them?\n\nSpeak for at least 40 seconds.','Expected: Empathetic communication, honest information, refreshment offer, rebooking assistance, calm demeanor.','B1','medium','roleplay_passenger','general','ground_staff',true,true,1),
('speaking','audio_response','Describe the de-icing process for an aircraft. What types of fluid are used and why is it important?\n\nSpeak for at least 40 seconds.','Expected: Type I and IV fluid, removal vs protection, holdover time, safety importance, when required.','B2','medium','oral_briefing','general','ground_staff',true,true,1),
('speaking','audio_response','You discovered a fuel spill near Gate 7. Describe what immediate actions you would take.\n\nSpeak for at least 30 seconds.','Expected: Alert others, cordon off area, notify fire services, prevent ignition sources, report to supervisor, spill kit.','A2','easy','roleplay_emergency','general','ground_staff',true,true,1),
('speaking','audio_response','Explain what a Load and Balance sheet is, why it is critical, and what can happen if an aircraft is loaded incorrectly.\n\nSpeak for at least 40 seconds.','Expected: Weight distribution, CG importance, safety implications, examples of incorrect loading consequences.','B2','hard','oral_briefing','general','ground_staff',true,true,1),
('speaking','audio_response','Roleplay: A passenger at the gate tells you their bag is too heavy and asks you to help them rearrange items between two bags. How would you assist while following safety rules?\n\nSpeak for at least 30 seconds.','Expected: Helpful attitude, weight limits explanation, offer assistance, security awareness.','A2','easy','roleplay_passenger','general','ground_staff',true,true,1),

-- Listening (12)
('listening','multiple_choice','[AUDIO] "Ramp Control, this is Gate 12. The aircraft has arrived on blocks. Requesting permission to approach for chock placement and ground power connection."\n\nWhat is being requested?\nA) Permission to fuel the aircraft\nB) Permission to approach for chocks and ground power\nC) Permission to board passengers\nD) Permission to push back','B','A2','easy','ground_ops_radio','general','ground_staff',true,true,1),
('listening','multiple_choice','[AUDIO] "Attention all ground staff: Wind is now gusting to 45 knots. All loose equipment must be secured immediately. Suspend loading operations on open stands until wind drops below 35 knots. Container loading may continue in sheltered positions only."\n\nAt what wind speed can loading resume on open stands?\nA) 45 knots\nB) Below 35 knots\nC) 25 knots\nD) Loading is permanently stopped','B','B1','medium','emergency_broadcast','general','ground_staff',true,true,1),
('listening','multiple_choice','[AUDIO] "Dispatcher to Ground 7: Flight TK2040 has a last-minute cargo addition — 320 kg of pharmaceutical goods, temperature sensitive, must go in the heated forward hold. Please confirm you can accommodate."\n\nWhere must the cargo be loaded?\nA) Aft hold\nB) Heated forward hold\nC) Bulk cargo area\nD) Passenger cabin','B','B1','medium','ground_ops_radio','general','ground_staff',true,true,1),
('listening','multiple_choice','[AUDIO] "This is the ramp supervisor. I need all teams to do a complete FOD walk of Stands 1 through 8 before the next wave of arrivals. That is in 20 minutes. Report findings on Channel 3."\n\nHow much time before the arrivals?\nA) 10 minutes\nB) 20 minutes\nC) 30 minutes\nD) 1 hour','B','A2','easy','ground_ops_radio','general','ground_staff',true,true,1),
('listening','multiple_choice','[AUDIO] "Ground crew at Stand 14, be advised: the aircraft arriving is a wide-body A330. You currently have narrow-body equipment staged. Please swap to wide-body bridge adaptor, belt loader, and tow bar before arrival in 15 minutes."\n\nWhat needs to change?\nA) The gate number\nB) Equipment must be swapped to wide-body\nC) The arrival time\nD) The crew assignment','B','B1','medium','ground_ops_radio','general','ground_staff',true,true,1),
('listening','multiple_choice','[AUDIO] "Security alert: An unattended bag has been found at Gate 22 boarding area. All ground operations at Gate 22 are suspended. Do not touch the bag. Security team is en route. Clear the area within 30 metres."\n\nWhat should you NOT do?\nA) Clear the area\nB) Touch the bag\nC) Wait for security\nD) Report to supervisor','B','A2','easy','emergency_broadcast','general','ground_staff',true,true,1),
('listening','multiple_choice','[AUDIO] "Load Control to Gate 5: Updated load instruction — move 2 bags from Position 4 aft to Position 2 forward. This is for CG adjustment. The captain requires revised trim before departure. Confirm when done."\n\nWhy are bags being moved?\nA) They are overweight\nB) For centre of gravity adjustment\nC) They are on the wrong flight\nD) The aft hold is full','B','B1','medium','ground_ops_radio','general','ground_staff',true,true,1),
('listening','multiple_choice','[AUDIO] "Fueling operator to Ground Control: Fueling of TC-FLY at Stand 9 is complete. Total uplift: 14,200 litres of Jet A-1. Fuel caps secured. Fueling equipment disconnecting now. Ground crew may resume operations around the aircraft."\n\nHow much fuel was loaded?\nA) 9,000 litres\nB) 12,000 litres\nC) 14,200 litres\nD) 16,000 litres','C','A2','easy','ground_ops_radio','fuel_system','ground_staff',true,true,1),
('listening','multiple_choice','[AUDIO] "Ramp supervisor to all teams: We have a medical emergency on the arriving flight at Gate 3. Ambulance is on the way. Please ensure the path from Gate 3 to the ambulance access point via Service Road B is completely clear. No vehicles in that area."\n\nWhat must be cleared?\nA) The runway\nB) The path from Gate 3 to ambulance access on Service Road B\nC) All gates\nD) The terminal building','B','B1','medium','emergency_broadcast','general','ground_staff',true,true,1),
('listening','multiple_choice','[AUDIO] "Ground to Flight Deck, TC-FLY. Pushback is approved by ATC, facing south. Confirm brakes released."\n"Brakes released, cleared to push."\n"Pushing back, facing south. Standby for start clearance."\n\nWhich direction is the aircraft being pushed?\nA) North\nB) South\nC) East\nD) West','B','A2','easy','ground_ops_radio','general','ground_staff',true,true,1),
('listening','multiple_choice','[AUDIO] "Attention: Ice and snow removal team to Taxiway Bravo between B2 and B6. Braking action reported poor by the last arrival. Airport operations has requested immediate treatment. Use glycol-based de-icer. Coordinate with Tower before entering taxiway."\n\nWhat is the braking condition?\nA) Good\nB) Medium\nC) Poor\nD) Not reported','C','B1','medium','ground_ops_radio','general','ground_staff',true,true,1),
('listening','multiple_choice','[AUDIO] "Hi, I am from the catering company. I have 12 trolleys for flight TK2090 at Gate 8. But the aircraft door L2 is not open yet. Can someone open it? We are running behind schedule and the flight departs in 40 minutes."\n\nWhat is the catering company''s problem?\nA) Wrong gate\nB) Aircraft door L2 is not open\nC) Not enough trolleys\nD) The flight is cancelled','B','A2','easy','ground_ops_radio','general','ground_staff',true,true,1);


-- ═══════════════════════════════════════════════════════════════
-- VERIFICATION QUERY
-- ═══════════════════════════════════════════════════════════════
SELECT role_tag, section, count(*) as question_count
FROM questions 
WHERE active = true AND is_latest = true
GROUP BY role_tag, section
ORDER BY role_tag, section;
