-- ═══════════════════════════════════════════════════════════════
-- CABIN CREW (role_tag = 'cabin_crew')
-- Flight attendants, cabin managers, pursers
-- 68 questions
-- ═══════════════════════════════════════════════════════════════

INSERT INTO questions (section, type, content, correct_answer, cefr_level, difficulty, competency_tag, aircraft_context, role_tag, active, is_latest, version_number) VALUES
-- Grammar (20)
('grammar','multiple_choice','The cabin crew _____ responsible for passenger safety during the flight.\nA) is\nB) are\nC) was\nD) been','B','A2','easy','structural_accuracy','general','cabin_crew',true,true,1),
('grammar','multiple_choice','All emergency equipment _____ checked before each flight.\nA) must be\nB) must\nC) must to\nD) must being','A','B1','medium','passive_voice','general','cabin_crew',true,true,1),
('grammar','multiple_choice','If a passenger _____ ill during the flight, we must provide first aid.\nA) becomes\nB) will become\nC) became\nD) becoming','A','B1','medium','conditional_forms','general','cabin_crew',true,true,1),
('grammar','multiple_choice','The purser asked the crew _____ they had completed the security check.\nA) that\nB) whether\nC) what\nD) which','B','B1','medium','structural_accuracy','general','cabin_crew',true,true,1),
('grammar','multiple_choice','Passengers _____ not allowed to smoke anywhere on the aircraft.\nA) is\nB) are\nC) was\nD) were','B','A2','easy','structural_accuracy','general','cabin_crew',true,true,1),
('grammar','fill_blank','Complete: The meal service was conducted _____ (efficient) despite turbulence.','efficiently','B1','medium','structural_accuracy','general','cabin_crew',true,true,1),
('grammar','multiple_choice','She has been working as a flight attendant _____ five years.\nA) since\nB) for\nC) during\nD) from','B','A2','easy','tense_usage','general','cabin_crew',true,true,1),
('grammar','multiple_choice','The overhead bins _____ opened carefully to prevent items from falling.\nA) should be\nB) should\nC) should to\nD) should being','A','B1','medium','passive_voice','general','cabin_crew',true,true,1),
('grammar','multiple_choice','_____ the seatbelt sign is on, passengers must remain seated.\nA) While\nB) During\nC) Although\nD) Despite','A','B1','medium','structural_accuracy','general','cabin_crew',true,true,1),
('grammar','multiple_choice','The child was crying _____ the entire flight.\nA) during\nB) while\nC) since\nD) for','A','A2','easy','phraseology_grammar','general','cabin_crew',true,true,1),
('grammar','fill_blank','Complete: Please speak _____ (clear) so the passengers can understand you.','clearly','A2','easy','structural_accuracy','general','cabin_crew',true,true,1),
('grammar','multiple_choice','By the time we served dinner, half the passengers _____ fallen asleep.\nA) had\nB) have\nC) has\nD) were','A','B2','medium','tense_usage','general','cabin_crew',true,true,1),
('grammar','multiple_choice','The life vest is located _____ your seat.\nA) under\nB) below\nC) beneath\nD) All are correct','D','A2','easy','phraseology_grammar','general','cabin_crew',true,true,1),
('grammar','multiple_choice','Neither tea _____ coffee is available during severe turbulence.\nA) or\nB) nor\nC) and\nD) but','B','B1','medium','structural_accuracy','general','cabin_crew',true,true,1),
('grammar','multiple_choice','The passenger demanded that the crew member _____ him an upgrade.\nA) give\nB) gives\nC) gave\nD) giving','A','B2','hard','structural_accuracy','general','cabin_crew',true,true,1),
('grammar','multiple_choice','We _____ just finished the safety demonstration when the captain made an announcement.\nA) had\nB) have\nC) has\nD) were','A','B1','medium','tense_usage','general','cabin_crew',true,true,1),
('grammar','fill_blank','Complete: Handle the medical kit _____ (careful) — it contains fragile items.','carefully','A2','easy','structural_accuracy','general','cabin_crew',true,true,1),
('grammar','multiple_choice','Each passenger _____ entitled to one carry-on bag and one personal item.\nA) is\nB) are\nC) were\nD) been','A','A2','easy','structural_accuracy','general','cabin_crew',true,true,1),
('grammar','multiple_choice','The duty-free cart _____ secured in the galley before landing.\nA) must be\nB) must\nC) has\nD) should','A','B1','medium','passive_voice','general','cabin_crew',true,true,1),
('grammar','multiple_choice','I wish I _____ more time to prepare the cabin before boarding.\nA) have\nB) had\nC) has\nD) having','B','B2','medium','conditional_forms','general','cabin_crew',true,true,1),

-- Reading (10)
('reading','multiple_choice','Read the cabin crew briefing card:\n\n"EMERGENCY EVACUATION: If the captain gives the EVACUATE command, cabin crew must: 1) Shout ''UNFASTEN SEATBELTS, COME THIS WAY'' 2) Open assigned exits if safe 3) Assess outside conditions before deploying slide 4) Direct passengers away from aircraft 5) Account for all passengers if possible."\n\nWhat must crew check before deploying the slide?\nA) Passenger count\nB) Outside conditions near the exit\nC) Whether the captain is ready\nD) If duty-free items are secured','B','B1','medium','safety_card_reading','general','cabin_crew',true,true,1),
('reading','multiple_choice','Read the service procedure:\n\n"SPECIAL MEALS: All pre-ordered special meals must be verified against the passenger manifest during boarding. Label each meal with the seat number. Serve special meals BEFORE the general meal service. If a special meal is missing, offer the closest available alternative and apologize to the passenger."\n\nWhen should special meals be served?\nA) After general meals\nB) Before general meal service\nC) At the same time\nD) Only if the passenger asks','B','A2','easy','sop_comprehension','general','cabin_crew',true,true,1),
('reading','multiple_choice','Read the medical protocol:\n\n"SUSPECTED HEART ATTACK: 1) Sit the passenger upright 2) Administer oxygen at 4L/min 3) Give 300mg aspirin (if not allergic) 4) Request doctor on board via PA 5) Inform flight deck — potential diversion 6) Complete medical event report form"\n\nWhat dosage of aspirin should be given?\nA) 100mg\nB) 200mg\nC) 300mg\nD) 500mg','C','B1','medium','technical_manual','general','cabin_crew',true,true,1),
('reading','multiple_choice','Read the passenger notice:\n\n"Dear Passengers, due to a technical issue with our catering system, only cold meals and sandwiches will be available on today''s flight. We apologize for the inconvenience and will provide a 500-mile bonus to your loyalty accounts as compensation. Hot beverages are still available."\n\nWhat compensation is offered?\nA) A free meal on the next flight\nB) 500 loyalty miles\nC) A full refund\nD) Free drinks','B','A2','easy','passenger_complaint','general','cabin_crew',true,true,1),
('reading','multiple_choice','Read the security briefing:\n\n"UNRULY PASSENGER PROTOCOL: Level 1 (verbal abuse) — Warn the passenger calmly. Level 2 (physical threat) — Inform the captain, request assistance from able-bodied passengers if needed. Level 3 (physical violence) — Restrain with approved equipment, captain to notify authorities at destination. Document ALL incidents on Form SEC-12."\n\nAt what level should the captain be informed?\nA) Level 1 only\nB) Level 2 and above\nC) Level 3 only\nD) Never — handle it yourself','B','B1','medium','sop_comprehension','general','cabin_crew',true,true,1),
('reading','multiple_choice','Read the galley checklist:\n\n"PRE-FLIGHT GALLEY CHECK:\n✓ All ovens functional and doors secured\n✓ Water boilers filled and operational\n✓ Catering loaded per manifest (verify quantities)\n✓ Dry ice containers sealed — DO NOT touch with bare hands\n✓ Waste containers empty with new bags\n✓ Fire extinguisher pin intact and pressure in green band"\n\nWhat hazard is mentioned about dry ice?\nA) It is flammable\nB) Do not touch with bare hands\nC) It can explode\nD) It contaminates food','B','A2','easy','sop_comprehension','general','cabin_crew',true,true,1),
('reading','multiple_choice','Read the policy update:\n\n"Effective 1 April 2026, all cabin crew must complete the updated Dangerous Goods Awareness training (DGA-2026). This replaces the previous DGA-2023 module. Training must be completed online before your next scheduled flight. Crew without valid DGA-2026 certification will not be rostered for duty."\n\nWhat happens if crew don''t complete the training?\nA) They receive a warning\nB) They are not scheduled for flights\nC) They must pay a fine\nD) Nothing happens','B','B1','medium','sop_comprehension','general','cabin_crew',true,true,1),
('reading','multiple_choice','Read the turbulence injury report:\n\n"During flight TK421 on 15 March, unexpected clear air turbulence was encountered at FL380. The seatbelt sign was off and cabin service was in progress. Three passengers and one crew member sustained minor injuries. The hot water boiler spilled, causing a burn to a crew member''s arm."\n\nWhat caused the crew member''s injury?\nA) Falling luggage\nB) Hot water from the boiler\nC) A passenger collision\nD) The emergency slide','B','B1','medium','incident_report','general','cabin_crew',true,true,1),
('reading','multiple_choice','Read the ditching preparation checklist:\n\n"DITCHING: 1) Brace position command 30 seconds before impact 2) All doors in MANUAL mode 3) Life vests to be inflated AFTER leaving aircraft 4) Deploy slide/rafts upon captain''s command 5) Take emergency kit and megaphone"\n\nWhen should life vests be inflated?\nA) Before impact\nB) Inside the aircraft\nC) After leaving the aircraft\nD) Only if in the water','C','B2','hard','safety_card_reading','general','cabin_crew',true,true,1),
('reading','multiple_choice','Read the crew rest regulation:\n\n"For flights exceeding 10 hours, an augmented crew is required. Rest periods must be at least 2 consecutive hours in an approved rest facility. No crew member shall exceed 12 hours of flight duty without a rest period."\n\nWhat is the minimum rest period for augmented crew?\nA) 1 hour\nB) 2 consecutive hours\nC) 3 hours\nD) 4 hours','B','B1','medium','sop_comprehension','general','cabin_crew',true,true,1),

-- Writing (8)
('writing','written_response','A passenger in seat 14A is extremely anxious about flying and is showing signs of a panic attack. Write a brief report (at least 50 words) describing the situation, what actions you took to help, and the outcome.','Model answer should include empathetic approach, calming techniques used, monitoring of passenger, communication with captain if needed.','B1','medium','incident_report','general','cabin_crew',true,true,1),
('writing','written_response','Write a professional passenger announcement (at least 40 words) welcoming passengers on board a flight from Istanbul to Paris. Include the flight time, weather at destination, and any service information.','Model answer should include greeting, flight details, weather info, meal service plan, professional tone.','A2','easy','cabin_announcement','general','cabin_crew',true,true,1),
('writing','written_response','A child travelling alone (unaccompanied minor, age 8) will be on your next flight. Write a handover note (at least 50 words) for the arrival crew describing the child, their seat number, who is meeting them, and any special needs.','Model answer should include child name, seat, guardian details at destination, dietary needs, emotional state during flight.','B1','medium','operational_message','general','cabin_crew',true,true,1),
('writing','written_response','You discovered that the aircraft''s defibrillator (AED) is showing an error code and may not be functional. Write a report to your purser (at least 50 words) about this medical equipment issue, your concern, and what action you recommend.','Model answer should include equipment ID, error description, safety concern, recommendation to inform captain and get replacement.','B1','medium','safety_report','general','cabin_crew',true,true,1),
('writing','written_response','A passenger has asked you to write a letter confirming that their connecting flight was missed due to a 2-hour departure delay. Write this confirmation letter (at least 60 words) on behalf of the airline.','Model answer should include flight details, delay reason, impact on connection, formal tone, next steps for rebooking.','B2','medium','passenger_complaint','general','cabin_crew',true,true,1),
('writing','written_response','Write an email to the catering company (at least 50 words) reporting that 15 meals were missing from today''s flight to London. Include the flight number, what was missing, and the impact on service.','Model answer should include specific numbers, flight details, impact on passengers, request for explanation and prevention.','B1','medium','operational_message','general','cabin_crew',true,true,1),
('writing','written_response','During boarding, you noticed a passenger carrying a suspiciously heavy carry-on bag that could exceed limits. When checked, it weighed 14kg (limit: 8kg). The passenger became aggressive when asked to check it in. Write an incident report (at least 60 words).','Model answer should include factual description, passenger behavior, crew response, resolution, documentation.','B2','hard','incident_report','general','cabin_crew',true,true,1),
('writing','written_response','Write a brief thank-you note (at least 40 words) to a passenger who helped calm other passengers during a turbulence event. This will be sent on behalf of the airline.','Model answer should be warm, professional, acknowledge specific actions, possibly offer loyalty miles or voucher.','A2','easy','passenger_complaint','general','cabin_crew',true,true,1),

-- Speaking (8)
('speaking','audio_response','Demonstrate the safety briefing you would give to passengers before takeoff. Include seatbelts, exits, oxygen masks, and life vests.\n\nSpeak for at least 45 seconds.','Expected: Complete safety demo script, clear pronunciation, professional cabin crew tone.','B1','medium','cabin_announcement','general','cabin_crew',true,true,1),
('speaking','audio_response','Roleplay: A passenger tells you they are allergic to nuts and is worried about the meal. Respond professionally, check options, and reassure them.\n\nSpeak for at least 30 seconds.','Expected: Empathetic response, allergy protocol awareness, alternative meal offer, reassurance.','A2','easy','roleplay_passenger','general','cabin_crew',true,true,1),
('speaking','audio_response','Roleplay: A passenger has had too much alcohol and is being loud and disturbing others. Handle the situation verbally. Explain what you would say to them.\n\nSpeak for at least 40 seconds.','Expected: Calm, firm approach. Refuse further alcohol. Offer water/food. Warn about consequences. Escalation protocol awareness.','B2','hard','roleplay_passenger','general','cabin_crew',true,true,1),
('speaking','audio_response','Explain the difference between an emergency landing and a ditching (water landing). What would cabin crew do differently in each case?\n\nSpeak for at least 40 seconds.','Expected: Land vs water distinction, brace commands, door modes, life vest inflation timing, raft deployment.','B2','medium','oral_briefing','general','cabin_crew',true,true,1),
('speaking','audio_response','You need to coordinate with another crew member during boarding. There is a wheelchair passenger who needs special assistance at Row 32. Explain what you need them to do.\n\nSpeak for at least 30 seconds.','Expected: Clear instruction, specific seat location, assistance type, pre-boarding arrangement, communication.','A2','easy','crew_coordination','general','cabin_crew',true,true,1),
('speaking','audio_response','A child on board is travelling alone for the first time and is very scared. Talk to the child to make them feel comfortable. Use simple, friendly language.\n\nSpeak for at least 30 seconds.','Expected: Child-friendly language, warmth, introducing yourself, explaining what will happen, offering activities/snacks.','A2','easy','roleplay_passenger','general','cabin_crew',true,true,1),
('speaking','audio_response','You are the purser conducting a pre-flight cabin crew briefing. Brief your team about today''s flight, including any special passengers, service plan, and emergency review.\n\nSpeak for at least 45 seconds.','Expected: Structured briefing, flight details, special pax (UM, wheelchair, VIP), service sequence, emergency assignment review.','B2','hard','crew_coordination','general','cabin_crew',true,true,1),
('speaking','audio_response','Describe what CRM means in the context of cabin crew. Why is teamwork important between cabin and flight deck? Give an example.\n\nSpeak for at least 40 seconds.','Expected: CRM definition, cabin-cockpit communication importance, sterile cockpit awareness, specific example.','B1','medium','oral_briefing','general','cabin_crew',true,true,1),

-- Listening (12)
('listening','multiple_choice','[AUDIO] "Cabin crew, this is the captain. We will be landing in approximately 20 minutes. Please begin cabin preparation for landing. Ensure all galleys are secured and passengers are seated with seatbelts fastened."\n\nHow much time until landing?\nA) 10 minutes\nB) 20 minutes\nC) 30 minutes\nD) 40 minutes','B','A2','easy','cockpit_communication','general','cabin_crew',true,true,1),
('listening','multiple_choice','[AUDIO] "Ladies and gentlemen, we would like to inform you that we have a doctor on board. If any medical professional is available, please identify yourself to a crew member. Thank you."\n\nWhat is being requested?\nA) A pilot\nB) A translator\nC) A medical professional\nD) Security personnel','C','A2','easy','cabin_announcement','general','cabin_crew',true,true,1),
('listening','multiple_choice','[AUDIO] "Purser to captain. We have a passenger in Row 22 showing signs of severe allergic reaction — facial swelling, difficulty breathing. We have administered the epinephrine auto-injector. Requesting you contact medical support on the ground."\n\nWhat treatment was given?\nA) Oxygen\nB) Aspirin\nC) Epinephrine auto-injector\nD) Bandage','C','B1','medium','emergency_broadcast','general','cabin_crew',true,true,1),
('listening','multiple_choice','[AUDIO] "Attention cabin crew at doors. We are now at the gate and the aircraft has been chocked. Please disarm your doors and cross-check. Disarm doors and cross-check."\n\nWhat must crew do with the doors?\nA) Open them immediately\nB) Disarm and cross-check\nC) Keep them armed\nD) Lock them permanently','B','A2','easy','cockpit_communication','general','cabin_crew',true,true,1),
('listening','multiple_choice','[AUDIO] "Hi, excuse me. I ordered a vegetarian meal when I booked, but you gave me chicken. I''m vegetarian — I cannot eat this. Can you please check if there is a vegetarian option available? My booking reference is ABC123."\n\nWhat is the passenger''s complaint?\nA) The meal is cold\nB) They received the wrong meal — they need vegetarian\nC) They don''t want any meal\nD) The chicken tastes bad','B','A2','easy','passenger_instruction','general','cabin_crew',true,true,1),
('listening','multiple_choice','[AUDIO] "Cabin crew, we are experiencing a pressurization problem. The cabin altitude is rising slowly. We are descending to FL100 as a precaution. Prepare the cabin for possible oxygen mask deployment. This is precautionary — not an emergency."\n\nWhat is happening to the cabin pressure?\nA) It is normal\nB) Cabin altitude is rising — pressurization issue\nC) The aircraft is climbing\nD) Oxygen is leaking','B','B2','hard','cockpit_communication','general','cabin_crew',true,true,1),
('listening','multiple_choice','[AUDIO] "Flight attendant, can you help me? My child has been sick — he vomited and now he has a fever. Do you have any medicine for children on board? He is 5 years old."\n\nWhat is wrong with the child?\nA) He is scared of flying\nB) He vomited and has a fever\nC) He lost his toy\nD) He is hungry','B','A2','easy','passenger_instruction','general','cabin_crew',true,true,1),
('listening','multiple_choice','[AUDIO] "This is your purser speaking to all crew. Just a reminder — on this sector we have 3 wheelchair passengers in rows 2, 15, and 28. Two unaccompanied minors in seats 8A and 8B. And a VIP guest in 1A — the CEO of our partner airline. Please ensure premium service."\n\nHow many wheelchair passengers are on this flight?\nA) 1\nB) 2\nC) 3\nD) 4','C','B1','medium','crew_coordination','general','cabin_crew',true,true,1),
('listening','multiple_choice','[AUDIO] "Crew, be advised: the forward lavatory is unserviceable. Please direct all passengers to use the mid-cabin and rear lavatories only. Maintenance will fix it at the destination. Place an OUT OF ORDER sign on the forward lav."\n\nWhich lavatory is not working?\nA) Rear lavatory\nB) Mid-cabin lavatory\nC) Forward lavatory\nD) All lavatories','C','A2','easy','cockpit_communication','general','cabin_crew',true,true,1),
('listening','multiple_choice','[AUDIO] "Cabin crew, slight change of plan. The captain has decided to hold for 15 minutes due to traffic at Istanbul. We have enough fuel. Please do NOT start the meal service yet — wait until we are past the hold. I will let you know when to begin."\n\nWhy should meal service be delayed?\nA) There are not enough meals\nB) The aircraft is in a holding pattern\nC) The oven is broken\nD) Passengers are sleeping','B','B1','medium','cockpit_communication','general','cabin_crew',true,true,1),
('listening','multiple_choice','[AUDIO] "Excuse me, flight attendant. I think the man in the seat behind me is unconscious. He is not responding when I tap his shoulder and his head is hanging to one side. I am a nurse — I can help if needed."\n\nWhat is being reported?\nA) A sleeping passenger\nB) A possibly unconscious passenger\nC) An angry passenger\nD) A lost child','B','B1','medium','emergency_broadcast','general','cabin_crew',true,true,1),
('listening','multiple_choice','[AUDIO] "All crew, this is a reminder: when we land in London, UK Border Force will conduct a random inspection. Please ensure all crew passports and visas are readily available. Also, do NOT throw away any customs declaration forms."\n\nWhat should crew have ready for London?\nA) Medical certificates\nB) Passports and visas\nC) Training certificates\nD) Meal receipts','B','A2','easy','ground_communication','general','cabin_crew',true,true,1);


-- ═══════════════════════════════════════════════════════════════
-- ATC (role_tag = 'atc')
-- Air Traffic Controllers
-- 68 questions
-- ═══════════════════════════════════════════════════════════════

INSERT INTO questions (section, type, content, correct_answer, cefr_level, difficulty, competency_tag, aircraft_context, role_tag, active, is_latest, version_number) VALUES
-- Grammar (20)
('grammar','multiple_choice','The controller _____ the aircraft to hold at the current position.\nA) instructed\nB) was instructing\nC) instruct\nD) has instruct','A','A2','easy','tense_usage','general','atc',true,true,1),
('grammar','multiple_choice','Traffic information _____ issued to all aircraft in the vicinity.\nA) was\nB) were\nC) is\nD) are','A','B1','medium','passive_voice','general','atc',true,true,1),
('grammar','multiple_choice','If the separation _____ below minimum, an alert will be triggered.\nA) falls\nB) will fall\nC) fell\nD) has fallen','A','B1','medium','conditional_forms','general','atc',true,true,1),
('grammar','multiple_choice','All flight plans _____ be filed at least 60 minutes before departure.\nA) must\nB) can\nC) might\nD) would','A','A2','easy','structural_accuracy','general','atc',true,true,1),
('grammar','multiple_choice','The radar showed that two aircraft _____ converging on the same point.\nA) are\nB) were\nC) is\nD) has been','B','B1','medium','tense_usage','general','atc',true,true,1),
('grammar','fill_blank','Complete: The controller spoke _____ (calm) during the emergency.','calmly','A2','easy','structural_accuracy','general','atc',true,true,1),
('grammar','multiple_choice','Neither approach _____ departure control could establish contact with the aircraft.\nA) or\nB) and\nC) nor\nD) but','C','B1','medium','structural_accuracy','general','atc',true,true,1),
('grammar','multiple_choice','The runway _____ been cleared for the next arrival.\nA) has\nB) have\nC) is\nD) are','A','A2','easy','passive_voice','general','atc',true,true,1),
('grammar','multiple_choice','We should _____ coordinated with the adjacent sector earlier.\nA) had\nB) have\nC) has\nD) having','B','B2','medium','structural_accuracy','general','atc',true,true,1),
('grammar','multiple_choice','The pilot reported that the visibility _____ improving.\nA) is\nB) was\nC) were\nD) are','B','B1','medium','tense_usage','general','atc',true,true,1),
('grammar','fill_blank','Complete: Separation was maintained _____ (safe) throughout the procedure.','safely','B1','medium','structural_accuracy','general','atc',true,true,1),
('grammar','multiple_choice','_____ receiving the clearance, the pilot read it back incorrectly.\nA) After\nB) Before\nC) While\nD) During','A','B1','medium','structural_accuracy','general','atc',true,true,1),
('grammar','multiple_choice','The aircraft _____ be vectored around the restricted area.\nA) will\nB) shall\nC) would\nD) Both A and B','D','B1','medium','phraseology_grammar','general','atc',true,true,1),
('grammar','multiple_choice','Each controller _____ required to log all communications.\nA) is\nB) are\nC) were\nD) been','A','A2','easy','structural_accuracy','general','atc',true,true,1),
('grammar','multiple_choice','By the time the relief controller arrived, I _____ been on position for 3 hours.\nA) had\nB) have\nC) was\nD) am','A','B2','medium','tense_usage','general','atc',true,true,1),
('grammar','multiple_choice','The aircraft was cleared to land _____ the condition that it would exit at taxiway Alpha.\nA) on\nB) at\nC) in\nD) with','A','B2','hard','phraseology_grammar','general','atc',true,true,1),
('grammar','fill_blank','Complete: The frequency was _____ (heavy) congested during peak hours.','heavily','B1','medium','structural_accuracy','general','atc',true,true,1),
('grammar','multiple_choice','How _____ aircraft are currently in the holding pattern?\nA) many\nB) much\nC) some\nD) any','A','A2','easy','structural_accuracy','general','atc',true,true,1),
('grammar','multiple_choice','The pilot asked _____ he could be given a direct routing.\nA) that\nB) if\nC) what\nD) which','B','B1','medium','structural_accuracy','general','atc',true,true,1),
('grammar','multiple_choice','Clearances _____ never be assumed — always wait for explicit confirmation.\nA) should\nB) must\nC) can\nD) might','A','B1','medium','phraseology_grammar','general','atc',true,true,1),

-- Reading (10)
('reading','multiple_choice','Read the ATC procedure:\n\n"WAKE TURBULENCE SEPARATION MINIMUMS:\n- Heavy behind Super: 6 NM\n- Medium behind Heavy: 5 NM\n- Light behind Heavy: 6 NM\n- Light behind Medium: 4 NM\nThese minimums apply on approach within 10 NM of the runway threshold."\n\nWhat separation is required for a Medium aircraft following a Heavy?\nA) 4 NM\nB) 5 NM\nC) 6 NM\nD) 3 NM','B','B1','medium','technical_manual','general','atc',true,true,1),
('reading','multiple_choice','Read the shift briefing:\n\n"Today''s traffic: Expected 340 movements (180 departures, 160 arrivals). Runway 36L/18R active for arrivals, 36R/18L for departures. VOR DME RWY 36L is unserviceable — ILS only. Wind forecast: 360/15 becoming 020/20 after 1500 local. Expect runway change to 05 after 1600."\n\nWhich approach is NOT available today?\nA) ILS Runway 36L\nB) VOR DME Runway 36L\nC) Visual approach\nD) GPS approach','B','B1','medium','sop_comprehension','general','atc',true,true,1),
('reading','multiple_choice','Read the regulation:\n\n"ICAO Annex 11: Separation standards shall be applied between IFR flights in controlled airspace. The minimum radar separation in terminal airspace is 3 NM. In en-route airspace, the minimum is 5 NM. For non-radar environments, procedural separation standards apply."\n\nWhat is the minimum radar separation in terminal airspace?\nA) 2 NM\nB) 3 NM\nC) 5 NM\nD) 10 NM','B','B2','hard','technical_manual','general','atc',true,true,1),
('reading','multiple_choice','Read the incident report:\n\n"At 1423Z, aircraft TK123 was cleared to cross Runway 27 at intersection B4. Simultaneously, aircraft PC456 was on short final for Runway 27. The conflict was detected by the runway incursion monitoring system. TK123 was instructed to HOLD POSITION. PC456 was sent around. Minimum separation was 0.8 NM."\n\nWhat system detected the conflict?\nA) The pilot of PC456\nB) Runway incursion monitoring system\nC) TCAS\nD) The tower supervisor','B','B2','hard','incident_report','general','atc',true,true,1),
('reading','multiple_choice','Read the frequency assignment:\n\n"Istanbul Approach: 120.7 (North Sector), 121.1 (South Sector)\nIstanbul Tower: 118.1 (Runway 36L/18R), 118.7 (Runway 36R/18L)\nIstanbul Ground: 121.9 (North), 121.6 (South)\nIstanbul Delivery: 128.5"\n\nWhich frequency should a departing aircraft contact for clearance?\nA) 118.1\nB) 121.9\nC) 128.5\nD) 120.7','C','A2','easy','sop_comprehension','general','atc',true,true,1),
('reading','multiple_choice','Read the ATIS:\n\n"Istanbul Ataturk information Foxtrot, time 1400Z. Runway in use 36L. Wind 340 degrees 12 knots. Visibility 9999 metres. Cloud few 030, scattered 080. Temperature 18, dewpoint 11. QNH 1016. Transition level FL70. ILS approach in use. Advise on initial contact you have information Foxtrot."\n\nWhat information letter is current?\nA) Echo\nB) Foxtrot\nC) Golf\nD) Delta','B','A2','easy','weather_report_reading','general','atc',true,true,1),
('reading','multiple_choice','Read the coordination procedure:\n\n"All aircraft entering Ankara FIR from Istanbul FIR must be transferred to Ankara Control on 132.6 at least 10 minutes before the FIR boundary. Aircraft must be at their cleared level and on the correct airway. Any deviations must be coordinated by phone before transfer."\n\nWhen must aircraft be transferred to Ankara?\nA) At the FIR boundary\nB) 10 minutes before the boundary\nC) 5 minutes before\nD) When the pilot requests','B','B1','medium','sop_comprehension','general','atc',true,true,1),
('reading','multiple_choice','Read the emergency procedure:\n\n"COMMUNICATIONS FAILURE: If an aircraft fails to respond on the assigned frequency: 1) Try all available frequencies including 121.5 2) Request other aircraft to relay 3) Try phone contact via airline operations 4) If no contact within 5 minutes, implement lost communications procedures per local SOP."\n\nWhat is the universal emergency frequency?\nA) 118.1\nB) 121.5\nC) 132.4\nD) 128.5','B','B1','medium','sop_comprehension','general','atc',true,true,1),
('reading','multiple_choice','Read the staffing requirement:\n\n"Minimum staffing for Istanbul Tower during peak hours (0600-2200 local): 2 Tower Controllers, 1 Ground Controller, 1 Clearance Delivery, 1 Supervisor. During off-peak (2200-0600): 1 Tower, 1 Ground (combined Delivery), 1 Supervisor."\n\nHow many tower controllers are needed during peak hours?\nA) 1\nB) 2\nC) 3\nD) 4','B','A2','easy','sop_comprehension','general','atc',true,true,1),
('reading','multiple_choice','Read the noise abatement procedure:\n\n"Between 2300 and 0600 local time, all departures from Runway 36R must follow the NOISE 1 procedure: Climb at maximum rate to 3000ft AGL, then reduce to normal climb gradient. No turns below 1500ft AGL. Continuous climb preferred — avoid level-offs below FL100."\n\nWhat is the minimum altitude for turns during NOISE 1 procedure?\nA) 500ft AGL\nB) 1000ft AGL\nC) 1500ft AGL\nD) 3000ft AGL','C','B2','medium','sop_comprehension','general','atc',true,true,1),

-- Writing (8)
('writing','written_response','Write a brief incident report (at least 60 words) about a runway incursion: a vehicle entered Runway 27 without clearance while an aircraft was on short final. Describe what happened, what actions you took, and the outcome.','Model answer should include time, involved parties, immediate action (go-around), coordination with ground, safety investigation.','B2','hard','incident_report','general','atc',true,true,1),
('writing','written_response','Write a shift handover note (at least 50 words) for the incoming controller. Include traffic situation, weather trends, any equipment issues, and ongoing coordination.','Model answer should include traffic count, active runways, weather changes, equipment status, pending coordinations.','B1','medium','operational_message','general','atc',true,true,1),
('writing','written_response','An aircraft has declared PAN-PAN due to a sick passenger and requests priority landing. Write the coordination message (at least 50 words) you would send to approach control and emergency services.','Model answer should include aircraft callsign, type of emergency, request, coordination with approach/fire/ambulance.','B1','medium','operational_message','general','atc',true,true,1),
('writing','written_response','Write a safety report (at least 60 words) about a near-miss between two aircraft on crossing taxiways. Include contributing factors and your recommendation to prevent recurrence.','Model answer should include factual description, separation lost, contributing factors, recommendation for signage/procedures.','B2','hard','safety_report','general','atc',true,true,1),
('writing','written_response','Write an email (at least 50 words) to the airport authority requesting that faded taxiway markings at intersection Alpha-3 be repainted. Explain the safety concern and urgency.','Model answer should include specific location, safety risk, near-miss potential, request timeline.','A2','easy','operational_message','general','atc',true,true,1),
('writing','written_response','A pilot has filed a complaint that they were kept in a hold for 35 minutes unnecessarily. Write a professional response (at least 60 words) explaining the reason for the hold (weather below minimums, traffic congestion).','Model answer should be professional, factual, explain weather/traffic situation, express understanding.','B2','medium','passenger_complaint','general','atc',true,true,1),
('writing','written_response','Write a brief training note (at least 50 words) explaining to a new controller what "sterile cockpit" means and why controllers should minimize unnecessary communications during critical phases of flight.','Model answer should define sterile cockpit, explain below 10000ft rule, impact on pilot workload, controller best practices.','B1','medium','technical_description','general','atc',true,true,1),
('writing','written_response','Write a proposal (at least 60 words) suggesting a new standard taxi route to reduce ground conflicts at your airport. Describe the current problem and your solution.','Model answer should include current conflict hotspot, proposed routing change, expected safety improvement, implementation suggestion.','B2','hard','operational_message','general','atc',true,true,1),

-- Speaking (8)
('speaking','audio_response','Issue ATC clearance to Turkish Airlines flight 1923 for departure: Runway 36L, ROMEO 1 ALPHA departure, climb FL180, squawk 4512, contact departure on 119.7.\n\nSpeak clearly using standard ATC phraseology.','Expected: Standard format, correct phraseology, runway, SID, altitude, squawk, frequency handoff.','B1','medium','atc_phraseology','general','atc',true,true,1),
('speaking','audio_response','An aircraft reports an engine failure after takeoff. Issue emergency instructions: clear the airspace, vector the aircraft for an immediate return, coordinate with emergency services.\n\nSpeak for at least 40 seconds.','Expected: Calm delivery, MAYDAY acknowledgment, priority handling, vectors, crash/fire alert, runway clearance.','B2','hard','roleplay_emergency','general','atc',true,true,1),
('speaking','audio_response','Explain what a "go-around" is, when a controller might instruct it, and what happens after. Use examples.\n\nSpeak for at least 40 seconds.','Expected: Definition, reasons (traffic, weather, runway occupied), procedure, new instructions, safety importance.','B1','medium','oral_briefing','general','atc',true,true,1),
('speaking','audio_response','You are handing over your position to the next controller. Brief them on: current traffic picture, weather, any ongoing situations, and anything to watch out for.\n\nSpeak for at least 45 seconds.','Expected: Structured handover, traffic count/positions, weather trend, special situations, equipment status.','B1','medium','crew_coordination','general','atc',true,true,1),
('speaking','audio_response','Issue taxi instructions to Pegasus flight 247 from Gate 22 to Runway 36L via taxiways Charlie, Alpha, and hold short of Runway 27 crossing.\n\nSpeak clearly using standard phraseology.','Expected: Correct callsign, specific taxi route, hold short instruction, readback expected.','A2','easy','atc_phraseology','general','atc',true,true,1),
('speaking','audio_response','Two aircraft are converging and you notice a potential conflict. Describe what you would do step by step to resolve the situation.\n\nSpeak for at least 40 seconds.','Expected: Identify conflict, issue immediate instruction (turn/climb/descend), traffic information, monitor, report.','B2','hard','roleplay_emergency','general','atc',true,true,1),
('speaking','audio_response','Explain the importance of read-back in ATC communications. Why is it critical? What happens when a read-back is incorrect?\n\nSpeak for at least 30 seconds.','Expected: Read-back purpose, error prevention, hear-back verification, examples of critical clearances.','B1','medium','oral_briefing','general','atc',true,true,1),
('speaking','audio_response','Roleplay: A pilot is requesting a shortcut — direct routing to save fuel. However, there is restricted airspace in the way. Deny the request professionally and offer an alternative.\n\nSpeak for at least 30 seconds.','Expected: Professional denial, reason (restricted area), alternative routing offered, helpful tone.','B1','medium','roleplay_atc','general','atc',true,true,1),

-- Listening (12)
('listening','multiple_choice','[AUDIO] "Istanbul Tower, Pegasus 245, ready for departure Runway 36 Left."\n"Pegasus 245, Istanbul Tower, wind 350 degrees 14 knots, Runway 36 Left, cleared for takeoff."\n\nWhat wind direction is reported?\nA) 250 degrees\nB) 350 degrees\nC) 360 degrees\nD) 140 degrees','B','A2','easy','atc_phraseology','general','atc',true,true,1),
('listening','multiple_choice','[AUDIO] "Approach, Turkish 1901, we have traffic on TCAS — appears to be same level, 12 o''clock, 5 miles."\n"Turkish 1901, roger, that is Pegasus 502, climbing to FL240, no conflict, he will be above you shortly."\n\nWhat is the other aircraft doing?\nA) Descending\nB) Climbing to FL240\nC) Landing\nD) Holding','B','B1','medium','atc_phraseology','general','atc',true,true,1),
('listening','multiple_choice','[AUDIO] "All stations, Istanbul Approach. Runway 36 Left is now closed due to a disabled aircraft. All arrivals will use Runway 36 Right ILS approach. Expect delays of 15 to 20 minutes."\n\nWhy is the runway closed?\nA) Construction\nB) A disabled aircraft\nC) Weather\nD) Scheduled maintenance','B','B1','medium','emergency_broadcast','general','atc',true,true,1),
('listening','multiple_choice','[AUDIO] "Ground, SunExpress 302 at holding point Alpha 1, ready for departure."\n"SunExpress 302, hold position. Landing traffic Runway 27. I say again, HOLD POSITION."\n\nWhat must the pilot do?\nA) Enter the runway\nB) Hold position and wait\nC) Take off immediately\nD) Taxi back to the gate','B','A2','easy','atc_phraseology','general','atc',true,true,1),
('listening','multiple_choice','[AUDIO] "Istanbul Delivery, AnadoluJet 670, requesting IFR clearance to Ankara, information Delta."\n"AnadoluJet 670, cleared to Ankara via KEMIK 2 BRAVO departure. Climb initially 5000 feet, expect FL310 10 minutes after departure. Squawk 3245."\n\nWhat is the initial climb altitude?\nA) 3000 feet\nB) 5000 feet\nC) FL310\nD) FL100','B','B1','medium','atc_phraseology','general','atc',true,true,1),
('listening','multiple_choice','[AUDIO] "Pan-Pan, Pan-Pan, Pan-Pan. Istanbul Approach, this is Atlas 891. We have a pressurization problem. Requesting descent to FL100 and priority approach."\n"Atlas 891, roger your Pan-Pan. Descend FL100. You are number 1 for approach. Emergency services on standby."\n\nWhat type of emergency is this?\nA) MAYDAY — immediate danger\nB) PAN-PAN — urgency\nC) No emergency\nD) Distress signal','B','B1','medium','emergency_broadcast','general','atc',true,true,1),
('listening','multiple_choice','[AUDIO] "Tower supervisor to all positions: we are now implementing low visibility procedures. RVR Runway 36L is 350 metres. Only CAT III equipped aircraft will be accepted for approach. Increase departure spacing to 3 minutes. Acknowledge."\n\nWhat is the current RVR?\nA) 550 metres\nB) 350 metres\nC) 1000 metres\nD) 3 metres','B','B2','hard','ground_ops_radio','general','atc',true,true,1),
('listening','multiple_choice','[AUDIO] "Istanbul Ground, Freebird 412, request taxi to the international terminal, Gate 15."\n"Freebird 412, taxi via taxiway Bravo, Charlie, hold short of runway 27 at Charlie 4."\n\nWhere must the aircraft hold?\nA) At Gate 15\nB) At Charlie 4 before Runway 27\nC) At the terminal\nD) At Bravo','B','A2','easy','atc_phraseology','general','atc',true,true,1),
('listening','multiple_choice','[AUDIO] "Ankara Center, Turkish 2023, request direct to ROMEO waypoint to save fuel. We are currently on the ALPHA 1 airway."\n"Turkish 2023, negative direct ROMEO. Restricted area TRA-15 is active. Suggest continue on ALPHA 1 airway and expect direct ROMEO after passing waypoint SIERRA."\n\nWhy was the direct route denied?\nA) Bad weather\nB) Restricted area is active\nC) Traffic conflict\nD) Runway closure','B','B1','medium','atc_phraseology','general','atc',true,true,1),
('listening','multiple_choice','[AUDIO] "All stations, ATIS update. Istanbul Airport information Golf, time 1600Z. Runway change in effect. Departures now Runway 05, arrivals Runway 05. Wind 050 degrees 18 knots. Transition level now FL80. All aircraft acknowledge new ATIS on initial contact."\n\nWhat has changed?\nA) The weather improved\nB) Runway direction has changed to 05\nC) The airport is closing\nD) New aircraft parking','B','B1','medium','atc_phraseology','general','atc',true,true,1),
('listening','multiple_choice','[AUDIO] "Shift supervisor to tower: I just received a phone call from the military. They are activating restricted area TRA-22 effective in 30 minutes, from FL200 to unlimited, for 2 hours. Please ensure all traffic is routed clear."\n\nHow long will the restricted area be active?\nA) 30 minutes\nB) 1 hour\nC) 2 hours\nD) Until further notice','C','B2','medium','ground_ops_radio','general','atc',true,true,1),
('listening','multiple_choice','[AUDIO] "Controller handover briefing: You have 8 aircraft on frequency — 3 arrivals sequenced for 36L, 2 departures holding at Alpha and Bravo, and 3 overflights at FL350-FL370. Weather is stable. The ILS is on test — it may drop out briefly, so have visual approach ready as backup."\n\nHow many aircraft are on frequency?\nA) 5\nB) 6\nC) 8\nD) 10','C','B1','medium','crew_coordination','general','atc',true,true,1);
