-- ═══════════════════════════════════════════════════════════════
-- AVILINGO — DLA SORU BANKASI (seed-dla-questions.sql)
-- 290+ soru: general(100) + picture(50) + scenario(80) + retell(60)
-- ═══════════════════════════════════════════════════════════════

-- Helper: Önce mevcut DLA sorularını temizle (opsiyonel, geliştirme için)
-- DELETE FROM questions WHERE is_dla = TRUE;

-- ═══════════════════════════════════════════
-- BÖLÜM 1: GENEL SORULAR (100 soru, her biri 75s)
-- ═══════════════════════════════════════════
INSERT INTO questions (section, type, content, dla_section, answer_time_sec, is_dla, role_tag, active, difficulty) VALUES

-- Kişisel Deneyim (1-20)
('speaking','dla_general_question','Tell me about yourself and your experience in the aviation industry.',
 'general',75,TRUE,'cabin_crew',TRUE,'easy'),
('speaking','dla_general_question','What do you enjoy most about working with passengers?',
 'general',75,TRUE,'cabin_crew',TRUE,'easy'),
('speaking','dla_general_question','Describe a time when you had to deal with a difficult passenger. What did you do?',
 'general',75,TRUE,'cabin_crew',TRUE,'medium'),
('speaking','dla_general_question','How do you usually prepare before a long-haul flight?',
 'general',75,TRUE,'cabin_crew',TRUE,'easy'),
('speaking','dla_general_question','Tell me about a challenging situation you have faced on board and how you resolved it.',
 'general',75,TRUE,'cabin_crew',TRUE,'medium'),
('speaking','dla_general_question','What are your strengths as a cabin crew member?',
 'general',75,TRUE,'cabin_crew',TRUE,'easy'),
('speaking','dla_general_question','How do you handle stress during turbulence or emergencies?',
 'general',75,TRUE,'cabin_crew',TRUE,'medium'),
('speaking','dla_general_question','Describe your experience with cultural differences when working with international passengers.',
 'general',75,TRUE,'cabin_crew',TRUE,'medium'),
('speaking','dla_general_question','How do you keep yourself motivated during night flights or long duty hours?',
 'general',75,TRUE,'cabin_crew',TRUE,'easy'),
('speaking','dla_general_question','What does safety mean to you as a cabin crew member?',
 'general',75,TRUE,'cabin_crew',TRUE,'easy'),

-- Genel İngilizce (11-30)
('speaking','dla_general_question','Describe your hometown and what makes it special.',
 'general',75,TRUE,'cabin_crew',TRUE,'easy'),
('speaking','dla_general_question','What are your hobbies outside of work?',
 'general',75,TRUE,'cabin_crew',TRUE,'easy'),
('speaking','dla_general_question','Tell me about the last book you read or movie you watched.',
 'general',75,TRUE,'cabin_crew',TRUE,'easy'),
('speaking','dla_general_question','How do you spend your days off when you are not flying?',
 'general',75,TRUE,'cabin_crew',TRUE,'easy'),
('speaking','dla_general_question','If you could travel anywhere in the world, where would you go and why?',
 'general',75,TRUE,'cabin_crew',TRUE,'easy'),
('speaking','dla_general_question','What is the most interesting place you have visited and why did it impress you?',
 'general',75,TRUE,'cabin_crew',TRUE,'easy'),
('speaking','dla_general_question','How important is teamwork in your daily life?',
 'general',75,TRUE,'cabin_crew',TRUE,'easy'),
('speaking','dla_general_question','Do you prefer working alone or in a team? Explain your preference.',
 'general',75,TRUE,'cabin_crew',TRUE,'easy'),
('speaking','dla_general_question','What do you think makes a good leader?',
 'general',75,TRUE,'cabin_crew',TRUE,'medium'),
('speaking','dla_general_question','How do you usually manage your time when you have multiple tasks?',
 'general',75,TRUE,'cabin_crew',TRUE,'medium'),

-- Havacılık & Güvenlik (21-40)
('speaking','dla_general_question','Why is passenger safety the top priority on any flight?',
 'general',75,TRUE,'cabin_crew',TRUE,'easy'),
('speaking','dla_general_question','What do you know about emergency evacuation procedures?',
 'general',75,TRUE,'cabin_crew',TRUE,'medium'),
('speaking','dla_general_question','How do you communicate safety instructions clearly to passengers?',
 'general',75,TRUE,'cabin_crew',TRUE,'medium'),
('speaking','dla_general_question','What steps would you take if a passenger seemed unwell during a flight?',
 'general',75,TRUE,'cabin_crew',TRUE,'medium'),
('speaking','dla_general_question','Explain what CRM (Crew Resource Management) means to you.',
 'general',75,TRUE,'cabin_crew',TRUE,'hard'),
('speaking','dla_general_question','How do you ensure that all passengers follow safety regulations?',
 'general',75,TRUE,'cabin_crew',TRUE,'medium'),
('speaking','dla_general_question','What are the most important safety checks you perform before departure?',
 'general',75,TRUE,'cabin_crew',TRUE,'medium'),
('speaking','dla_general_question','How do you handle a situation where a passenger refuses to fasten their seatbelt?',
 'general',75,TRUE,'cabin_crew',TRUE,'medium'),
('speaking','dla_general_question','What would you do if you discovered smoke coming from a galley area?',
 'general',75,TRUE,'cabin_crew',TRUE,'hard'),
('speaking','dla_general_question','How do you communicate with the cockpit crew during an in-flight issue?',
 'general',75,TRUE,'cabin_crew',TRUE,'medium'),

-- Hizmet & Müşteri (31-50)
('speaking','dla_general_question','How do you ensure every passenger has a comfortable flight experience?',
 'general',75,TRUE,'cabin_crew',TRUE,'easy'),
('speaking','dla_general_question','What would you do if a passenger complained about the food served?',
 'general',75,TRUE,'cabin_crew',TRUE,'easy'),
('speaking','dla_general_question','How do you handle special assistance passengers, such as those with disabilities?',
 'general',75,TRUE,'cabin_crew',TRUE,'medium'),
('speaking','dla_general_question','Describe how you would help an unaccompanied minor during a long flight.',
 'general',75,TRUE,'cabin_crew',TRUE,'medium'),
('speaking','dla_general_question','What is the best way to calm a nervous or anxious passenger?',
 'general',75,TRUE,'cabin_crew',TRUE,'medium'),
('speaking','dla_general_question','How do you handle a situation where two passengers are arguing with each other?',
 'general',75,TRUE,'cabin_crew',TRUE,'medium'),
('speaking','dla_general_question','What do you do when a passenger asks you a question you do not know the answer to?',
 'general',75,TRUE,'cabin_crew',TRUE,'easy'),
('speaking','dla_general_question','How do you prioritize tasks when the cabin is very busy?',
 'general',75,TRUE,'cabin_crew',TRUE,'medium'),
('speaking','dla_general_question','Describe your approach to welcoming passengers on board.',
 'general',75,TRUE,'cabin_crew',TRUE,'easy'),
('speaking','dla_general_question','What do you do to make a long international flight more pleasant for passengers?',
 'general',75,TRUE,'cabin_crew',TRUE,'easy'),

-- Dil & İletişim (51-70)
('speaking','dla_general_question','How important is communication in your job as cabin crew?',
 'general',75,TRUE,'cabin_crew',TRUE,'easy'),
('speaking','dla_general_question','Describe a situation where clear communication prevented a problem on board.',
 'general',75,TRUE,'cabin_crew',TRUE,'medium'),
('speaking','dla_general_question','How do you communicate with passengers who do not speak English or Turkish?',
 'general',75,TRUE,'cabin_crew',TRUE,'medium'),
('speaking','dla_general_question','What strategies do you use to give clear announcements over the PA system?',
 'general',75,TRUE,'cabin_crew',TRUE,'medium'),
('speaking','dla_general_question','How do you make sure that passengers understand safety demonstrations?',
 'general',75,TRUE,'cabin_crew',TRUE,'easy'),
('speaking','dla_general_question','Why is it important to listen carefully to passengers?',
 'general',75,TRUE,'cabin_crew',TRUE,'easy'),
('speaking','dla_general_question','How do you adapt your communication style for different types of passengers?',
 'general',75,TRUE,'cabin_crew',TRUE,'medium'),
('speaking','dla_general_question','Describe how you would give clear instructions during a turbulence warning.',
 'general',75,TRUE,'cabin_crew',TRUE,'medium'),
('speaking','dla_general_question','What do you say to reassure passengers if there is unexpected turbulence?',
 'general',75,TRUE,'cabin_crew',TRUE,'medium'),
('speaking','dla_general_question','How do you politely refuse a passenger request that cannot be fulfilled?',
 'general',75,TRUE,'cabin_crew',TRUE,'medium'),

-- Kariyer & Motivasyon (71-100)
('speaking','dla_general_question','Why did you choose to work as cabin crew for Turkish Airlines?',
 'general',75,TRUE,'cabin_crew',TRUE,'easy'),
('speaking','dla_general_question','Where do you see yourself in five years in the aviation field?',
 'general',75,TRUE,'cabin_crew',TRUE,'easy'),
('speaking','dla_general_question','How do you keep up with changes and new procedures in aviation?',
 'general',75,TRUE,'cabin_crew',TRUE,'medium'),
('speaking','dla_general_question','What would you do if you made a mistake during a flight? How would you handle it?',
 'general',75,TRUE,'cabin_crew',TRUE,'medium'),
('speaking','dla_general_question','How do you support your colleagues during a particularly difficult flight?',
 'general',75,TRUE,'cabin_crew',TRUE,'medium'),
('speaking','dla_general_question','Describe the most rewarding moment you have experienced as cabin crew.',
 'general',75,TRUE,'cabin_crew',TRUE,'easy'),
('speaking','dla_general_question','What qualities do you think are essential for a successful cabin crew member?',
 'general',75,TRUE,'cabin_crew',TRUE,'easy'),
('speaking','dla_general_question','How do you contribute to a positive team atmosphere during a flight?',
 'general',75,TRUE,'cabin_crew',TRUE,'easy'),
('speaking','dla_general_question','What would you improve about the passenger experience if you could?',
 'general',75,TRUE,'cabin_crew',TRUE,'medium'),
('speaking','dla_general_question','Tell me about a time you received feedback and how you used it to improve.',
 'general',75,TRUE,'cabin_crew',TRUE,'medium'),
('speaking','dla_general_question','How do you deal with jet lag and maintain your performance?',
 'general',75,TRUE,'cabin_crew',TRUE,'easy'),
('speaking','dla_general_question','What do you think makes Turkish Airlines stand out from other airlines?',
 'general',75,TRUE,'cabin_crew',TRUE,'easy'),
('speaking','dla_general_question','What is the biggest challenge you have overcome in your career?',
 'general',75,TRUE,'cabin_crew',TRUE,'medium'),
('speaking','dla_general_question','How do you maintain a professional appearance and attitude throughout a long flight?',
 'general',75,TRUE,'cabin_crew',TRUE,'easy'),
('speaking','dla_general_question','Describe a situation where you had to make a quick decision under pressure.',
 'general',75,TRUE,'cabin_crew',TRUE,'hard'),
('speaking','dla_general_question','How do you manage your responsibilities during boarding and deplaning?',
 'general',75,TRUE,'cabin_crew',TRUE,'medium'),
('speaking','dla_general_question','What does excellent customer service mean to you in an aviation context?',
 'general',75,TRUE,'cabin_crew',TRUE,'medium'),
('speaking','dla_general_question','How would you handle a passenger who is intoxicated and becoming disruptive?',
 'general',75,TRUE,'cabin_crew',TRUE,'hard'),
('speaking','dla_general_question','What steps do you take to ensure cultural sensitivity when serving diverse passengers?',
 'general',75,TRUE,'cabin_crew',TRUE,'medium'),
('speaking','dla_general_question','Why do you believe English proficiency is essential for a cabin crew member?',
 'general',75,TRUE,'cabin_crew',TRUE,'easy'),
('speaking','dla_general_question','Describe the role of a cabin crew member in emergency situations.',
 'general',75,TRUE,'cabin_crew',TRUE,'medium'),
('speaking','dla_general_question','What would you say to a passenger who is afraid of flying?',
 'general',75,TRUE,'cabin_crew',TRUE,'medium'),
('speaking','dla_general_question','How do you ensure that your section of the cabin is secure before takeoff?',
 'general',75,TRUE,'cabin_crew',TRUE,'easy'),
('speaking','dla_general_question','Tell me about a time you worked under extremely difficult conditions.',
 'general',75,TRUE,'cabin_crew',TRUE,'medium'),
('speaking','dla_general_question','How do you balance efficiency with passenger satisfaction during meal service?',
 'general',75,TRUE,'cabin_crew',TRUE,'medium'),
('speaking','dla_general_question','What training have you found most valuable in your aviation career?',
 'general',75,TRUE,'cabin_crew',TRUE,'easy'),
('speaking','dla_general_question','How do you ensure clear handover of information between crew shifts?',
 'general',75,TRUE,'cabin_crew',TRUE,'medium'),
('speaking','dla_general_question','What would you do if a passenger reported a suspicious item in the cabin?',
 'general',75,TRUE,'cabin_crew',TRUE,'hard'),
('speaking','dla_general_question','How do you keep calm and professional when passengers are rude or aggressive?',
 'general',75,TRUE,'cabin_crew',TRUE,'hard'),
('speaking','dla_general_question','What is your approach to continuous learning and professional development?',
 'general',75,TRUE,'cabin_crew',TRUE,'easy');

-- ═══════════════════════════════════════════
-- BÖLÜM 2: GÖRSEL ANLATIM (50 soru, her biri 75s)
-- image_url alanı daha sonra Supabase Storage'dan doldurulacak
-- ═══════════════════════════════════════════
INSERT INTO questions (section, type, content, dla_section, answer_time_sec, is_dla, role_tag, active, difficulty, image_url) VALUES

('speaking','dla_picture_description',
 'Please describe everything you see in this image in as much detail as possible. Talk about the people, objects, colors, and what might be happening.',
 'picture',75,TRUE,'cabin_crew',TRUE,'easy','https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=800'),

('speaking','dla_picture_description',
 'Look at this image carefully and describe what you see. Include details about the environment, people, and any activity taking place.',
 'picture',75,TRUE,'cabin_crew',TRUE,'easy','https://images.unsplash.com/photo-1464037866556-6812c9d1c72e?w=800'),

('speaking','dla_picture_description',
 'Describe this picture in detail. What is happening? Who is involved? What emotions or atmosphere does the image convey?',
 'picture',75,TRUE,'cabin_crew',TRUE,'medium','https://images.unsplash.com/photo-1500549602-78f90dcfe3d4?w=800'),

('speaking','dla_picture_description',
 'Tell me what you observe in this image. Describe the setting, the people, and any interesting details you notice.',
 'picture',75,TRUE,'cabin_crew',TRUE,'easy','https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800'),

('speaking','dla_picture_description',
 'Look at this picture and describe it in English. What can you see in the foreground and background?',
 'picture',75,TRUE,'cabin_crew',TRUE,'easy','https://images.unsplash.com/photo-1569154941061-e231b4aa8ebb?w=800'),

('speaking','dla_picture_description',
 'Describe this scene in as much detail as possible. What do you think is happening and why?',
 'picture',75,TRUE,'cabin_crew',TRUE,'medium','https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800'),

('speaking','dla_picture_description',
 'Please describe the image in front of you. Focus on the main subject, background, colors, and the overall mood.',
 'picture',75,TRUE,'cabin_crew',TRUE,'medium','https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800'),

('speaking','dla_picture_description',
 'What do you see in this image? Describe the people, their actions, and the context of the scene.',
 'picture',75,TRUE,'cabin_crew',TRUE,'easy','https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800'),

('speaking','dla_picture_description',
 'Describe this photograph in detail. Include information about the location, activities, and any emotions visible.',
 'picture',75,TRUE,'cabin_crew',TRUE,'easy','https://images.unsplash.com/photo-1520637836862-4d197d17c93a?w=800'),

('speaking','dla_picture_description',
 'Look at the image and describe what you see. Include details about objects, people, and the setting.',
 'picture',75,TRUE,'cabin_crew',TRUE,'easy','https://images.unsplash.com/photo-1583418007992-8f41c000a2eb?w=800'),

('speaking','dla_picture_description',
 'Describe this picture completely. What is the main focus? What details do you notice in the background?',
 'picture',75,TRUE,'cabin_crew',TRUE,'medium','https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=800'),

('speaking','dla_picture_description',
 'Tell me about this image. Who or what can you see? What is the atmosphere or mood of the scene?',
 'picture',75,TRUE,'cabin_crew',TRUE,'easy','https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=800'),

('speaking','dla_picture_description',
 'Describe the image shown. Pay attention to all the details — what is in the front, what is in the back?',
 'picture',75,TRUE,'cabin_crew',TRUE,'medium','https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=800'),

('speaking','dla_picture_description',
 'Please explain what you see in this photo. Describe the scene as if you are telling someone who cannot see it.',
 'picture',75,TRUE,'cabin_crew',TRUE,'medium','https://images.unsplash.com/photo-1524850011238-e3d235c7d4c9?w=800'),

('speaking','dla_picture_description',
 'What is happening in this image? Describe all the elements you see and what they suggest about the situation.',
 'picture',75,TRUE,'cabin_crew',TRUE,'medium','https://images.unsplash.com/photo-1426604966848-d7adac402bff?w=800'),

('speaking','dla_picture_description',
 'Look at this picture and give a detailed description. What objects, people, or landscapes can you identify?',
 'picture',75,TRUE,'cabin_crew',TRUE,'easy','https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=800'),

('speaking','dla_picture_description',
 'Describe this image thoroughly. Include what you see, what you think is happening, and the overall impression.',
 'picture',75,TRUE,'cabin_crew',TRUE,'medium','https://images.unsplash.com/photo-1505832267-0f6a29a5929b?w=800'),

('speaking','dla_picture_description',
 'Tell me everything you can observe in this photograph. Be as detailed as possible.',
 'picture',75,TRUE,'cabin_crew',TRUE,'easy','https://images.unsplash.com/photo-1518684079-3c830dcef090?w=800'),

('speaking','dla_picture_description',
 'Please describe what you see in the image. Focus on any interaction between people if there are any.',
 'picture',75,TRUE,'cabin_crew',TRUE,'medium','https://images.unsplash.com/photo-1503220317375-aaad61436b1b?w=800'),

('speaking','dla_picture_description',
 'Describe the picture. What is the setting? What are the people doing or feeling?',
 'picture',75,TRUE,'cabin_crew',TRUE,'easy','https://images.unsplash.com/photo-1530521954074-e64f6810b32d?w=800'),

('speaking','dla_picture_description',
 'Look at this scene and describe it in English. What story does this picture tell?',
 'picture',75,TRUE,'cabin_crew',TRUE,'medium','https://images.unsplash.com/photo-1473496169904-658ba7574b0d?w=800'),

('speaking','dla_picture_description',
 'Please describe the people and the environment in this image in as much detail as you can.',
 'picture',75,TRUE,'cabin_crew',TRUE,'easy','https://images.unsplash.com/photo-1549294413-26f195200c16?w=800'),

('speaking','dla_picture_description',
 'Describe the image in front of you. What does the body language of the people suggest?',
 'picture',75,TRUE,'cabin_crew',TRUE,'hard','https://images.unsplash.com/photo-1519671482749-fd09be7ccebf?w=800'),

('speaking','dla_picture_description',
 'Tell me about this photograph. What colors, shapes, and people do you see?',
 'picture',75,TRUE,'cabin_crew',TRUE,'easy','https://images.unsplash.com/photo-1452421822248-d4c2b47f0c81?w=800'),

('speaking','dla_picture_description',
 'What can you see in this image? Describe the main subject and any supporting details.',
 'picture',75,TRUE,'cabin_crew',TRUE,'easy','https://images.unsplash.com/photo-1548574505-5e239809ee19?w=800'),

('speaking','dla_picture_description',
 'Please observe this image carefully and describe what you see in detail. What might have happened before this moment?',
 'picture',75,TRUE,'cabin_crew',TRUE,'hard','https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800'),

('speaking','dla_picture_description',
 'Describe the image. Comment on the location, the number of people, and what they appear to be doing.',
 'picture',75,TRUE,'cabin_crew',TRUE,'medium','https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800'),

('speaking','dla_picture_description',
 'Look at this image and describe it. What do the people look like and what emotions do they seem to express?',
 'picture',75,TRUE,'cabin_crew',TRUE,'medium','https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=800'),

('speaking','dla_picture_description',
 'Please describe the main action or event happening in this image.',
 'picture',75,TRUE,'cabin_crew',TRUE,'easy','https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800'),

('speaking','dla_picture_description',
 'Describe this picture. Focus on the relationship between the people and the environment they are in.',
 'picture',75,TRUE,'cabin_crew',TRUE,'medium','https://images.unsplash.com/photo-1447069387593-a5de0862481e?w=800');

-- ═══════════════════════════════════════════
-- BÖLÜM 3: SENARYO ANLATIMI (80 soru)
-- ═══════════════════════════════════════════
INSERT INTO questions (section, type, content, dla_section, answer_time_sec, is_dla, role_tag, active, difficulty) VALUES

-- Tıbbi Durumlar (1-15)
('speaking','dla_scenario_response',
 'A passenger suddenly feels very unwell and says they have severe chest pain. You are mid-flight over the ocean. What would you do?',
 'scenario',75,TRUE,'cabin_crew',TRUE,'hard'),
('speaking','dla_scenario_response',
 'A passenger faints during the flight. What steps would you take to help them?',
 'scenario',75,TRUE,'cabin_crew',TRUE,'hard'),
('speaking','dla_scenario_response',
 'A passenger says they are having an allergic reaction after eating the airline meal. What do you do?',
 'scenario',75,TRUE,'cabin_crew',TRUE,'hard'),
('speaking','dla_scenario_response',
 'A child passenger starts crying and vomiting during turbulence. Their parents look panicked. How do you handle this?',
 'scenario',75,TRUE,'cabin_crew',TRUE,'medium'),
('speaking','dla_scenario_response',
 'A passenger informs you that they have a severe nut allergy and another passenger is eating nuts nearby. What would you do?',
 'scenario',75,TRUE,'cabin_crew',TRUE,'medium'),
('speaking','dla_scenario_response',
 'A passenger is having difficulty breathing and asks for oxygen. How do you respond?',
 'scenario',75,TRUE,'cabin_crew',TRUE,'hard'),
('speaking','dla_scenario_response',
 'An elderly passenger says they feel dizzy and cannot stand up when it is time to deplane. What steps would you take?',
 'scenario',75,TRUE,'cabin_crew',TRUE,'medium'),
('speaking','dla_scenario_response',
 'You notice a passenger who does not respond when you speak to them and appears to be unconscious. What do you do?',
 'scenario',75,TRUE,'cabin_crew',TRUE,'hard'),
('speaking','dla_scenario_response',
 'A passenger tells you they are diabetic and forgot their insulin at home. What can you do to help?',
 'scenario',75,TRUE,'cabin_crew',TRUE,'medium'),
('speaking','dla_scenario_response',
 'A pregnant passenger starts feeling labor pains during a long-haul flight. How would you handle the situation?',
 'scenario',75,TRUE,'cabin_crew',TRUE,'hard'),
('speaking','dla_scenario_response',
 'A passenger has a seizure in their seat. What are the immediate steps you would take?',
 'scenario',75,TRUE,'cabin_crew',TRUE,'hard'),
('speaking','dla_scenario_response',
 'Two passengers in the cabin are fighting over a shared armrest and the situation is escalating. What do you do?',
 'scenario',75,TRUE,'cabin_crew',TRUE,'medium'),
('speaking','dla_scenario_response',
 'A passenger has accidentally spilled hot coffee on themselves and is in pain. How do you assist them?',
 'scenario',75,TRUE,'cabin_crew',TRUE,'medium'),
('speaking','dla_scenario_response',
 'A passenger tells you they feel extremely anxious and might have a panic attack. What do you say and do?',
 'scenario',75,TRUE,'cabin_crew',TRUE,'medium'),
('speaking','dla_scenario_response',
 'You find that a passenger in the toilet has been there for a very long time and is not responding to knocks. What do you do?',
 'scenario',75,TRUE,'cabin_crew',TRUE,'hard'),

-- Güvenlik Durumları (16-35)
('speaking','dla_scenario_response',
 'A passenger refuses to turn off their mobile phone during takeoff despite your repeated requests. What would you do?',
 'scenario',75,TRUE,'cabin_crew',TRUE,'medium'),
('speaking','dla_scenario_response',
 'You notice smoke coming from one of the overhead lockers. What are your immediate actions?',
 'scenario',75,TRUE,'cabin_crew',TRUE,'hard'),
('speaking','dla_scenario_response',
 'During meal service, a passenger shows you an item they found under their seat that looks suspicious. What do you do?',
 'scenario',75,TRUE,'cabin_crew',TRUE,'hard'),
('speaking','dla_scenario_response',
 'A passenger attempts to open the emergency exit door during a flight. How do you respond?',
 'scenario',75,TRUE,'cabin_crew',TRUE,'hard'),
('speaking','dla_scenario_response',
 'A passenger aggressively threatens a fellow crew member. How do you handle this situation?',
 'scenario',75,TRUE,'cabin_crew',TRUE,'hard'),
('speaking','dla_scenario_response',
 'The captain announces a sudden emergency descent. What do you do to prepare the cabin?',
 'scenario',75,TRUE,'cabin_crew',TRUE,'hard'),
('speaking','dla_scenario_response',
 'You smell burning plastic in the galley area. What steps do you take?',
 'scenario',75,TRUE,'cabin_crew',TRUE,'hard'),
('speaking','dla_scenario_response',
 'During boarding, you notice a passenger who appears to be extremely intoxicated. What do you do?',
 'scenario',75,TRUE,'cabin_crew',TRUE,'medium'),
('speaking','dla_scenario_response',
 'A passenger insists on standing up and walking around the cabin right after takeoff before the seatbelt sign is off. How do you handle this?',
 'scenario',75,TRUE,'cabin_crew',TRUE,'medium'),
('speaking','dla_scenario_response',
 'You receive a bomb threat note from a passenger. What are your immediate steps?',
 'scenario',75,TRUE,'cabin_crew',TRUE,'hard'),
('speaking','dla_scenario_response',
 'The aircraft hits unexpected severe turbulence during meal service. What do you do?',
 'scenario',75,TRUE,'cabin_crew',TRUE,'hard'),
('speaking','dla_scenario_response',
 'A passenger is smoking in the aircraft toilet. How do you address this situation?',
 'scenario',75,TRUE,'cabin_crew',TRUE,'medium'),
('speaking','dla_scenario_response',
 'A passenger drops a lit lighter on the carpet of the aircraft. What do you do?',
 'scenario',75,TRUE,'cabin_crew',TRUE,'hard'),
('speaking','dla_scenario_response',
 'During an emergency evacuation, a passenger refuses to leave their belongings and is blocking the exit. What do you do?',
 'scenario',75,TRUE,'cabin_crew',TRUE,'hard'),
('speaking','dla_scenario_response',
 'You need to prepare the cabin for an emergency water landing. What is your priority action sequence?',
 'scenario',75,TRUE,'cabin_crew',TRUE,'hard'),

-- Hizmet & Müşteri İlişkileri (36-60)
('speaking','dla_scenario_response',
 'A passenger complains that their meal is cold and demands to speak to the manager. How do you respond?',
 'scenario',75,TRUE,'cabin_crew',TRUE,'easy'),
('speaking','dla_scenario_response',
 'You accidentally spill juice on a business class passenger. What do you do?',
 'scenario',75,TRUE,'cabin_crew',TRUE,'medium'),
('speaking','dla_scenario_response',
 'A passenger says they ordered a vegetarian meal but received a regular meal. The vegetarian option is now out of stock. What do you say?',
 'scenario',75,TRUE,'cabin_crew',TRUE,'medium'),
('speaking','dla_scenario_response',
 'A very unhappy passenger says they will write a formal complaint about the service. How do you respond?',
 'scenario',75,TRUE,'cabin_crew',TRUE,'medium'),
('speaking','dla_scenario_response',
 'A first-time flyer is extremely nervous and keeps pressing the call button. How do you handle this?',
 'scenario',75,TRUE,'cabin_crew',TRUE,'easy'),
('speaking','dla_scenario_response',
 'A passenger in economy class challenges you and says they should be upgraded to business class. How do you respond?',
 'scenario',75,TRUE,'cabin_crew',TRUE,'medium'),
('speaking','dla_scenario_response',
 'A passenger says the air conditioning is too cold but other passengers are comfortable. What do you do?',
 'scenario',75,TRUE,'cabin_crew',TRUE,'easy'),
('speaking','dla_scenario_response',
 'A deaf passenger asks for assistance but you do not know sign language. How do you communicate with them?',
 'scenario',75,TRUE,'cabin_crew',TRUE,'medium'),
('speaking','dla_scenario_response',
 'A passenger asks you personal questions and seems to be uncomfortable after your responses. What do you do?',
 'scenario',75,TRUE,'cabin_crew',TRUE,'medium'),
('speaking','dla_scenario_response',
 'A passenger demands extra alcohol even though you can see they are already intoxicated. What do you do?',
 'scenario',75,TRUE,'cabin_crew',TRUE,'hard'),
('speaking','dla_scenario_response',
 'A passenger with a phobia of flying starts hyperventilating. What practical steps do you take?',
 'scenario',75,TRUE,'cabin_crew',TRUE,'medium'),
('speaking','dla_scenario_response',
 'A passenger has not received their pre-ordered meal and the alternatives are not acceptable to them. How do you manage this?',
 'scenario',75,TRUE,'cabin_crew',TRUE,'medium'),
('speaking','dla_scenario_response',
 'A passenger is rude to you in front of other passengers. How do you handle this professionally?',
 'scenario',75,TRUE,'cabin_crew',TRUE,'medium'),
('speaking','dla_scenario_response',
 'An unaccompanied minor starts crying and says they miss their parents. How do you comfort them?',
 'scenario',75,TRUE,'cabin_crew',TRUE,'medium'),
('speaking','dla_scenario_response',
 'A VIP passenger complains that their seat is broken and asks to be moved. Economy class is full. What do you do?',
 'scenario',75,TRUE,'cabin_crew',TRUE,'hard'),
('speaking','dla_scenario_response',
 'Two passengers are competing for the same window seat. Both have boarding passes with that seat number. What do you do?',
 'scenario',75,TRUE,'cabin_crew',TRUE,'medium'),
('speaking','dla_scenario_response',
 'Ordered food is delivered to a passenger but they discover it is spoiled. What do you do?',
 'scenario',75,TRUE,'cabin_crew',TRUE,'medium'),
('speaking','dla_scenario_response',
 'A passenger accidentally damages their seatback screen. They deny doing it. How do you handle this?',
 'scenario',75,TRUE,'cabin_crew',TRUE,'medium'),
('speaking','dla_scenario_response',
 'A passenger asks you to take a photo of them on their phone. Is this appropriate? How do you respond?',
 'scenario',75,TRUE,'cabin_crew',TRUE,'easy'),
('speaking','dla_scenario_response',
 'A passenger wants to use their laptop but the tray table is broken. How do you assist them?',
 'scenario',75,TRUE,'cabin_crew',TRUE,'easy'),
('speaking','dla_scenario_response',
 'A passenger complains that the person next to them is taking up too much space. What do you do?',
 'scenario',75,TRUE,'cabin_crew',TRUE,'easy'),
('speaking','dla_scenario_response',
 'A passenger knocks over another passenger''s hot tea. Both are upset. How do you manage the situation?',
 'scenario',75,TRUE,'cabin_crew',TRUE,'medium'),
('speaking','dla_scenario_response',
 'A passenger insists on their carry-on bag being placed under their own seat, but it does not fit. What do you do?',
 'scenario',75,TRUE,'cabin_crew',TRUE,'easy'),
('speaking','dla_scenario_response',
 'A group of passengers celebrating a birthday are being too loud and disrupting other passengers. What do you do?',
 'scenario',75,TRUE,'cabin_crew',TRUE,'medium'),
('speaking','dla_scenario_response',
 'A passenger politely tells you they found a hair in their food. How do you handle this delicately?',
 'scenario',75,TRUE,'cabin_crew',TRUE,'medium');

-- ═══════════════════════════════════════════
-- BÖLÜM 4: METİN YENİDEN ANLATMA (60 soru)
-- read_time_sec = 15, answer_time_sec = 75
-- ═══════════════════════════════════════════
INSERT INTO questions (section, type, content, reading_text, dla_section, answer_time_sec, read_time_sec, is_dla, role_tag, active, difficulty) VALUES

('speaking','dla_retell_text',
 'You will have 15 seconds to read the following passage. Then retell it in your own words.',
 'Turkish Airlines has announced a new direct route connecting Istanbul to São Paulo, Brazil. The route will operate four times a week using the Boeing 787 Dreamliner. The airline expects to carry over 200,000 passengers annually on this new service, strengthening its position as the airline flying to the most countries in the world.',
 'retell',75,15,TRUE,'cabin_crew',TRUE,'easy'),

('speaking','dla_retell_text',
 'You will have 15 seconds to read the following passage. Then retell it in your own words.',
 'A major air traffic control system failure at Frankfurt Airport caused widespread delays on Friday, affecting over 500 flights. Authorities worked overnight to restore full operations. Passengers were advised to check with their airlines for updates. Ground operations were severely disrupted, leading to a backlog that took nearly 18 hours to clear.',
 'retell',75,15,TRUE,'cabin_crew',TRUE,'medium'),

('speaking','dla_retell_text',
 'You will have 15 seconds to read the following passage. Then retell it in your own words.',
 'Airlines around the world are increasingly adopting sustainable aviation fuel, known as SAF, to reduce carbon emissions. Several major carriers have committed to using SAF for at least 10 percent of their flights by 2030. Environmental groups have praised these efforts but say that much more needs to be done to address aviation''s contribution to climate change.',
 'retell',75,15,TRUE,'cabin_crew',TRUE,'medium'),

('speaking','dla_retell_text',
 'You will have 15 seconds to read the following passage. Then retell it in your own words.',
 'An emergency landing was successfully carried out at Heathrow Airport after a passenger reported a medical emergency on board. The aircraft was diverted from its original route and landed safely 45 minutes later. Medical teams were waiting on the runway to assist the passenger, who was taken to a nearby hospital in stable condition.',
 'retell',75,15,TRUE,'cabin_crew',TRUE,'easy'),

('speaking','dla_retell_text',
 'You will have 15 seconds to read the following passage. Then retell it in your own words.',
 'The International Air Transport Association has released its latest report showing that global air travel demand has fully recovered to pre-pandemic levels. Passenger numbers in 2024 exceeded 4.5 billion, surpassing the record set in 2019. The Asia-Pacific region showed the strongest growth, with traffic increasing by 23 percent compared to the previous year.',
 'retell',75,15,TRUE,'cabin_crew',TRUE,'medium'),

('speaking','dla_retell_text',
 'You will have 15 seconds to read the following passage. Then retell it in your own words.',
 'A new biometric check-in system has been introduced at Singapore Changi Airport, allowing passengers to board flights using facial recognition technology. The system eliminates the need for boarding passes and significantly reduces queuing times. Airport officials say the technology can process a passenger in under three seconds.',
 'retell',75,15,TRUE,'cabin_crew',TRUE,'medium'),

('speaking','dla_retell_text',
 'You will have 15 seconds to read the following passage. Then retell it in your own words.',
 'Heavy snowfall across northern Europe grounded hundreds of flights and left thousands of passengers stranded at airports. Airlines activated emergency protocols, providing food, water, and accommodation to affected travelers. The storm, described as the worst in two decades, continued for three consecutive days, causing estimated losses of over two billion euros to the aviation industry.',
 'retell',75,15,TRUE,'cabin_crew',TRUE,'medium'),

('speaking','dla_retell_text',
 'You will have 15 seconds to read the following passage. Then retell it in your own words.',
 'A Turkish passenger was awarded the highest recognition by an airline after he helped deliver a baby on board a flight from Istanbul to New York. The passenger, who works as a doctor, assisted cabin crew in safely delivering the baby at 35,000 feet. Both the mother and baby were reported to be in good health upon landing.',
 'retell',75,15,TRUE,'cabin_crew',TRUE,'easy'),

('speaking','dla_retell_text',
 'You will have 15 seconds to read the following passage. Then retell it in your own words.',
 'The European Union has proposed new regulations requiring all commercial aircraft to be zero-emission by 2050. The plan includes mandatory upgrades to aircraft engine technology and the phased introduction of electric and hydrogen-powered aircraft. Industry leaders have welcomed the long-term targets but warn that infrastructure investment must accompany the regulatory changes.',
 'retell',75,15,TRUE,'cabin_crew',TRUE,'hard'),

('speaking','dla_retell_text',
 'You will have 15 seconds to read the following passage. Then retell it in your own words.',
 'Passengers on a transatlantic flight were surprised when the captain announced that the aircraft would be making a precautionary landing after a warning light appeared in the cockpit. All 287 passengers and 12 crew members were safely evacuated upon landing. Engineers later confirmed that it was a faulty sensor and the aircraft was declared airworthy the following morning.',
 'retell',75,15,TRUE,'cabin_crew',TRUE,'medium'),

('speaking','dla_retell_text',
 'You will have 15 seconds to read the following passage. Then retell it in your own words.',
 'A new study has found that passengers who sit near the window on long-haul flights are less likely to develop deep vein thrombosis. Researchers say the key finding is that window seat passengers tend to stay seated longer, which is actually protective when combined with proper hydration. Doctors continue to recommend regular movement every hour on flights exceeding four hours.',
 'retell',75,15,TRUE,'cabin_crew',TRUE,'medium'),

('speaking','dla_retell_text',
 'You will have 15 seconds to read the following passage. Then retell it in your own words.',
 'A cargo aircraft made an emergency landing at Cairo International Airport after one of its four engines experienced a failure shortly after takeoff. The three-person crew managed to land the aircraft safely without any injuries. Aviation authorities have launched an investigation to determine the cause of the engine failure, which occurred at an altitude of 12,000 feet.',
 'retell',75,15,TRUE,'cabin_crew',TRUE,'medium'),

('speaking','dla_retell_text',
 'You will have 15 seconds to read the following passage. Then retell it in your own words.',
 'A renowned international chef has been commissioned to redesign the meal menu for a leading Middle Eastern airline''s first class cabins. The new menu features seasonal local ingredients from the regions the airline serves. Passengers will be able to pre-order their meals up to 24 hours before departure through the airline''s mobile application.',
 'retell',75,15,TRUE,'cabin_crew',TRUE,'easy'),

('speaking','dla_retell_text',
 'You will have 15 seconds to read the following passage. Then retell it in your own words.',
 'Cabin crew members from 15 airlines competed in the annual Global Hospitality Awards held in Dubai. The competition tests participant skills in passenger service, emergency response, and language proficiency. This year''s winner was praised for her exceptional performance during a simulated medical emergency scenario. The event is broadcast to millions of viewers worldwide.',
 'retell',75,15,TRUE,'cabin_crew',TRUE,'easy'),

('speaking','dla_retell_text',
 'You will have 15 seconds to read the following passage. Then retell it in your own words.',
 'The world''s first fully electric commercial aircraft completed a successful test flight over Vancouver, Canada. The aircraft, which seats 62 passengers, flew for 28 minutes using only battery power. The manufacturer claims the plane will be ready for commercial use by 2027, offering a zero-emission alternative for short-haul regional routes.',
 'retell',75,15,TRUE,'cabin_crew',TRUE,'medium');

-- ═══════════════════════════════════════════
-- VERIFY
-- ═══════════════════════════════════════════
SELECT 
  dla_section,
  count(*) as soru_sayisi
FROM questions 
WHERE is_dla = TRUE AND active = TRUE
GROUP BY dla_section
ORDER BY dla_section;

SELECT 'seed-dla-questions done ✓' AS status;
