-- ═══════════════════════════════════════════════════════════════
-- AVILINGO V2 — COMPLETE QUESTION SET
-- 6 roles + general pool · All 6 question types · A2–C1 levels
-- Run this AFTER migration-role-tags.sql
-- ═══════════════════════════════════════════════════════════════

-- STEP 1: Clean all existing questions
DELETE FROM grade_details WHERE grade_id IN (SELECT id FROM grades);
DELETE FROM grades;
DELETE FROM exam_answers;
DELETE FROM exam_question_sets;
DELETE FROM questions;

-- ═══════════════════════════════════════════════════════════════
-- GENERAL POOL (role_tag = 'general')
-- These questions appear in ALL roles' exams
-- 40 questions: 15 grammar, 5 reading, 5 writing, 5 speaking, 10 listening
-- ═══════════════════════════════════════════════════════════════

INSERT INTO questions (section, type, content, correct_answer, cefr_level, difficulty, competency_tag, aircraft_context, role_tag, active, is_latest, version_number) VALUES
-- Grammar (general)
('grammar','multiple_choice','All passengers _____ fasten their seatbelts during takeoff and landing.\nA) must\nB) can\nC) might\nD) would','A','A2','easy','structural_accuracy','general','general',true,true,1),
('grammar','multiple_choice','The flight _____ delayed due to severe weather conditions.\nA) is\nB) was\nC) were\nD) been','B','A2','easy','tense_usage','general','general',true,true,1),
('grammar','multiple_choice','If the weather _____ worse, we will divert to an alternate airport.\nA) gets\nB) will get\nC) got\nD) has gotten','A','B1','medium','conditional_forms','general','general',true,true,1),
('grammar','multiple_choice','The safety demonstration _____ before every departure.\nA) is performed\nB) performs\nC) performing\nD) was perform','A','A2','easy','passive_voice','general','general',true,true,1),
('grammar','multiple_choice','Neither the captain _____ the first officer reported any anomalies.\nA) or\nB) and\nC) nor\nD) but','C','B1','medium','structural_accuracy','general','general',true,true,1),
('grammar','multiple_choice','Emergency exits are located _____ both sides of the aircraft.\nA) in\nB) on\nC) at\nD) by','B','A2','easy','phraseology_grammar','general','general',true,true,1),
('grammar','multiple_choice','The crew _____ been briefed on the new security procedures.\nA) has\nB) have\nC) is\nD) was','B','B1','medium','tense_usage','general','general',true,true,1),
('grammar','fill_blank','Complete the sentence: The aircraft was inspected _____ (thorough) before the flight.','thoroughly','B1','medium','structural_accuracy','general','general',true,true,1),
('grammar','fill_blank','Complete the sentence: Safety is _____ (important) than schedule in aviation.','more important','A2','easy','structural_accuracy','general','general',true,true,1),
('grammar','multiple_choice','By the time we landed, the ground crew _____ the gate ready.\nA) had made\nB) has made\nC) made\nD) making','A','B2','medium','tense_usage','general','general',true,true,1),
('grammar','multiple_choice','The report _____ submitted by the end of the shift.\nA) must be\nB) must\nC) must to be\nD) must being','A','B1','medium','passive_voice','general','general',true,true,1),
('grammar','fill_blank','Complete the sentence: He asked _____ (polite) if there were any seats available.','politely','A2','easy','structural_accuracy','general','general',true,true,1),
('grammar','multiple_choice','_____ the delay, all passengers remained calm.\nA) Despite\nB) Although\nC) However\nD) Because','A','B1','medium','structural_accuracy','general','general',true,true,1),
('grammar','multiple_choice','The new regulation requires that all staff _____ additional training.\nA) complete\nB) completes\nC) completing\nD) to complete','A','B2','medium','structural_accuracy','general','general',true,true,1),
('grammar','multiple_choice','How _____ luggage are you carrying today?\nA) many\nB) much\nC) some\nD) few','B','A2','easy','structural_accuracy','general','general',true,true,1),

-- Reading (general)
('reading','multiple_choice','Read the following safety notice:\n\n"IMPORTANT: In the event of a cabin depressurization, oxygen masks will drop automatically from the panel above your seat. Pull the mask towards you, place it over your nose and mouth, and breathe normally. Secure your own mask before assisting others."\n\nWhat should you do FIRST when oxygen masks drop?\nA) Help the person next to you\nB) Pull the mask towards you and put it on\nC) Call a flight attendant\nD) Move to the nearest exit','B','A2','easy','safety_card_reading','general','general',true,true,1),
('reading','multiple_choice','Read the NOTAM:\n\n"NOTAM B0412/26 — ILS RWY 05 unserviceable from 20 MAR to 22 MAR 2026. VOR/DME approach available. Contact tower on 118.1 for updated approach information."\n\nWhich approach system is NOT working?\nA) VOR/DME\nB) ILS for Runway 05\nC) Tower communications\nD) All approach systems','B','B1','medium','notam_interpretation','general','general',true,true,1),
('reading','multiple_choice','Read the weather report:\n\n"METAR LTBA 180900Z 33012KT 9999 FEW040 SCT100 18/08 Q1015 NOSIG"\n\nWhat is the visibility at this airport?\nA) 3300 metres\nB) 9999 metres (10km or more)\nC) 1800 metres\nD) 4000 metres','B','B2','hard','weather_report_reading','general','general',true,true,1),
('reading','multiple_choice','Read the regulation excerpt:\n\n"All aviation personnel must report any incident, no matter how minor, within 24 hours using the Safety Reporting System. Failure to report may result in disciplinary action. All reports are treated confidentially."\n\nWithin what timeframe must incidents be reported?\nA) Immediately\nB) Within 24 hours\nC) Within 48 hours\nD) By end of the week','B','A2','easy','sop_comprehension','general','general',true,true,1),
('reading','multiple_choice','Read the memo:\n\n"Due to runway construction at Gate B, all departures between 0600-1400 local will use Taxiway Charlie instead of Taxiway Alpha. Ground crews must verify routing with ATC before each pushback. This change is effective from 19 March to 5 April 2026."\n\nWhen does this routing change end?\nA) 19 March 2026\nB) 5 April 2026\nC) When construction is done\nD) After 1400 local','B','B1','medium','sop_comprehension','general','general',true,true,1),

-- Writing (general)
('writing','written_response','Write a short email (at least 50 words) to your colleague explaining that tomorrow''s morning briefing has been moved from 0800 to 0900 due to a schedule change. Include the reason and ask them to confirm they received the message.','Model: Subject: Briefing Time Change. Hi [Name], I am writing to let you know that tomorrow morning briefing has been rescheduled from 0800 to 0900. This change is due to an updated shift rotation schedule from management. Please arrive at the briefing room by 0855. Could you please confirm that you have received this message? Thank you.','A2','easy','operational_message','general','general',true,true,1),
('writing','written_response','You witnessed an unsafe situation at work — a vehicle was driving too fast on the airport ramp near aircraft. Write a safety report (at least 60 words) describing what you saw, when and where it happened, and what action should be taken.','Model: Safety Incident Report. Date: 18 March 2026, Time: 1430 local. Location: Ramp area near Gate 7. I observed a baggage tractor driving at excessive speed approximately 40 km/h in the aircraft movement area near Stand 7B. The vehicle passed within 3 metres of parked aircraft TC-FLY without slowing down. No ground personnel were wearing high-visibility vests in the area. I recommend reviewing CCTV footage, identifying the driver, and conducting a ramp safety refresher for all ground vehicle operators.','B1','medium','safety_report','general','general',true,true,1),
('writing','written_response','A passenger has complained that their special meal was not loaded on the flight. Write a professional response letter (at least 60 words) apologizing and explaining what steps will be taken to prevent this in the future.','Model answer should include apology, acknowledgment, explanation of corrective action, and offer of goodwill gesture.','B1','medium','passenger_complaint','general','general',true,true,1),
('writing','written_response','Write a brief handover note (at least 50 words) for the next shift, summarizing what was completed during your shift, what tasks are still pending, and any important information they need to know.','Model answer should include completed tasks, pending items, and critical notes for next shift.','A2','easy','operational_message','general','general',true,true,1),
('writing','written_response','Your team needs to work overtime this weekend due to increased flight schedules. Write an email (at least 60 words) to your team members informing them about the overtime, the reason, and the compensation they will receive.','Model answer should include clear information about overtime schedule, reason, and compensation details.','B2','medium','operational_message','general','general',true,true,1),

-- Speaking (general)
('speaking','audio_response','Introduce yourself as if you are at a job interview for an aviation position. Include your name, your experience, why you chose aviation, and what skills you bring to the role.\n\nSpeak for at least 45 seconds.','Expected: Clear introduction, relevant experience mention, motivation for aviation, key skills. Professional tone.','B1','medium','oral_briefing','general','general',true,true,1),
('speaking','audio_response','Describe what you would do if you noticed a fire in your work area at the airport. Explain the steps you would take in order.\n\nSpeak for at least 30 seconds.','Expected: Alert others, activate alarm, use fire extinguisher if safe, evacuate, call emergency services. Clear sequence.','A2','easy','roleplay_emergency','general','general',true,true,1),
('speaking','audio_response','Your colleague is new and asks you: "What are the most important safety rules at the airport?" Explain at least 4 safety rules.\n\nSpeak for at least 40 seconds.','Expected: PPE requirements, FOD awareness, vehicle safety, restricted areas, emergency procedures, communication protocols.','B1','medium','ground_communication','general','general',true,true,1),
('speaking','audio_response','Describe the weather conditions you can see outside right now. Then explain how bad weather can affect airport operations.\n\nSpeak for at least 30 seconds.','Expected: Description of current weather, impact on visibility, delays, de-icing needs, wind effects on landing/takeoff.','A2','easy','oral_briefing','general','general',true,true,1),
('speaking','audio_response','You need to make an announcement to passengers about a 45-minute flight delay. Deliver the announcement professionally, including the reason (technical check) and what the airline will provide (refreshments).\n\nSpeak for at least 30 seconds.','Expected: Professional tone, clear information, empathy, solution offered.','B2','medium','cabin_announcement','general','general',true,true,1),

-- Listening (general)
('listening','multiple_choice','[AUDIO] "Attention all staff. This is a reminder that the mandatory fire safety drill will take place tomorrow at 1400 hours in the main hangar. All personnel must attend. Please wear your safety equipment. The drill will last approximately 30 minutes."\n\nWhen is the fire drill?\nA) Today at 1400\nB) Tomorrow at 1400\nC) Tomorrow at 1300\nD) Next week','B','A2','easy','emergency_broadcast','general','general',true,true,1),
('listening','multiple_choice','[AUDIO] "Good morning. Due to fog, visibility is currently 400 metres. All ground operations are suspended until visibility improves to at least 550 metres. Stand by for further updates on frequency 121.9."\n\nWhat is the current visibility?\nA) 550 metres\nB) 400 metres\nC) 121 metres\nD) 900 metres','B','B1','medium','ground_ops_radio','general','general',true,true,1),
('listening','multiple_choice','[AUDIO] "All personnel, be advised that Taxiway Delta is closed for maintenance between intersection D2 and D5. Use Taxiway Echo as an alternative. This closure will remain in effect until further notice."\n\nWhich alternative taxiway should be used?\nA) Taxiway Delta\nB) Taxiway Bravo\nC) Taxiway Echo\nD) Taxiway Alpha','C','A2','easy','ground_ops_radio','general','general',true,true,1),
('listening','multiple_choice','[AUDIO] "Tower, this is Turkish 1842 requesting pushback from Gate 12. We have information Bravo, ready to copy taxi instructions."\n\nWhat is the aircraft requesting?\nA) Landing clearance\nB) Pushback from Gate 12\nC) Runway change\nD) Fuel request','B','B1','medium','atc_phraseology','general','general',true,true,1),
('listening','multiple_choice','[AUDIO] "Maintenance Control, this is Line Station 3. We have completed the daily inspection on aircraft TC-SKY. All items satisfactory except the left nose wheel tire which shows 2mm tread remaining. Minimum is 3mm. Requesting tire change before next departure."\n\nWhat problem was found?\nA) Engine oil is low\nB) Left nose wheel tire tread is below minimum\nC) The brakes need changing\nD) The inspection was not completed','B','B1','medium','ground_ops_radio','general','general',true,true,1),
('listening','multiple_choice','[AUDIO] "Ladies and gentlemen, the captain has turned on the fasten seatbelt sign. We are expecting some turbulence ahead. Please return to your seats and keep your seatbelts fastened until the sign is turned off. Cabin crew, please be seated."\n\nWhy was the seatbelt sign turned on?\nA) The plane is landing\nB) Turbulence is expected\nC) The plane is taking off\nD) There is an emergency','B','A2','easy','cabin_announcement','general','general',true,true,1),
('listening','multiple_choice','[AUDIO] "Ground, Pegasus 247 Heavy. We need to return to the gate. We have a medical emergency on board. Requesting priority handling and an ambulance at Gate 8."\n\nWhat type of emergency is reported?\nA) Engine failure\nB) Medical emergency\nC) Fire on board\nD) Fuel leak','B','B1','medium','emergency_broadcast','general','general',true,true,1),
('listening','multiple_choice','[AUDIO] "Attention ground crew. Aircraft at Stand 14 will be departing in 20 minutes. Please ensure all ground equipment is removed and the area is clear. Headset operator, confirm ready for pushback."\n\nHow soon will the aircraft depart?\nA) In 10 minutes\nB) In 20 minutes\nC) In 30 minutes\nD) Immediately','B','A2','easy','ground_ops_radio','general','general',true,true,1),
('listening','multiple_choice','[AUDIO] "This is the operations manager speaking. I want to remind everyone that we have a VIP flight departing at 1600 today from Gate 1. All security protocols must be strictly followed. Additional screening is required for all personnel accessing the gate area."\n\nWhat special requirement is mentioned?\nA) No personnel allowed near Gate 1\nB) Additional security screening for personnel\nC) The flight is cancelled\nD) Gate 1 is closed','B','B1','medium','ground_ops_radio','general','general',true,true,1),
('listening','multiple_choice','[AUDIO] "Control tower, SunExpress 502. We have landed on Runway 36 and vacated via taxiway Alpha 3. Request taxi to Gate 22."\n\nWhat has the aircraft just done?\nA) Taken off\nB) Landed and left the runway\nC) Requested fuel\nD) Reported an emergency','B','B1','medium','atc_phraseology','general','general',true,true,1);


-- ═══════════════════════════════════════════════════════════════
-- FLIGHT DECK (role_tag = 'flight_deck')
-- Pilots, co-pilots, flight engineers
-- 68 questions
-- ═══════════════════════════════════════════════════════════════

INSERT INTO questions (section, type, content, correct_answer, cefr_level, difficulty, competency_tag, aircraft_context, role_tag, active, is_latest, version_number) VALUES
-- Grammar (20)
('grammar','multiple_choice','The captain informed ATC that they _____ unable to maintain the assigned altitude.\nA) are\nB) were\nC) is\nD) being','B','B1','medium','tense_usage','general','flight_deck',true,true,1),
('grammar','multiple_choice','Permission to descend _____ granted by approach control.\nA) is\nB) was\nC) were\nD) been','B','A2','easy','passive_voice','general','flight_deck',true,true,1),
('grammar','multiple_choice','If we _____ enough fuel, we would not need to divert.\nA) have\nB) had\nC) has\nD) having','B','B2','medium','conditional_forms','general','flight_deck',true,true,1),
('grammar','multiple_choice','The first officer _____ the pre-flight checklist while the captain reviewed the weather.\nA) completed\nB) was completing\nC) has completed\nD) completes','B','B1','medium','tense_usage','general','flight_deck',true,true,1),
('grammar','multiple_choice','ATC instructed us _____ hold over the ROMEO waypoint.\nA) for\nB) to\nC) at\nD) on','B','A2','easy','phraseology_grammar','general','flight_deck',true,true,1),
('grammar','multiple_choice','The autopilot _____ disconnected automatically when the system detected a fault.\nA) is\nB) was\nC) has\nD) were','B','B1','medium','passive_voice','general','flight_deck',true,true,1),
('grammar','fill_blank','Complete: The weather at our destination is _____ (significant) worse than forecast.','significantly','B1','medium','structural_accuracy','general','flight_deck',true,true,1),
('grammar','multiple_choice','We need to declare an emergency _____ our hydraulic system has failed.\nA) because\nB) although\nC) despite\nD) unless','A','B1','medium','structural_accuracy','general','flight_deck',true,true,1),
('grammar','multiple_choice','The TCAS _____ a resolution advisory just before we reached FL350.\nA) issued\nB) has issued\nC) issues\nD) issuing','A','B2','medium','tense_usage','general','flight_deck',true,true,1),
('grammar','fill_blank','Complete: The captain made the decision _____ (quick) to go around.','quickly','A2','easy','structural_accuracy','general','flight_deck',true,true,1),
('grammar','multiple_choice','Neither the altimeter _____ the airspeed indicator was showing correct readings.\nA) or\nB) nor\nC) and\nD) but','B','B1','medium','structural_accuracy','general','flight_deck',true,true,1),
('grammar','multiple_choice','We _____ fly above FL410 due to aircraft performance limitations.\nA) cannot\nB) must not\nC) should\nD) may','A','B1','medium','phraseology_grammar','general','flight_deck',true,true,1),
('grammar','multiple_choice','The windshear warning _____ activated during our final approach to Runway 23.\nA) is\nB) was\nC) has\nD) were','B','A2','easy','passive_voice','general','flight_deck',true,true,1),
('grammar','multiple_choice','By the time we reached the alternate, we _____ been flying for 6 hours.\nA) had\nB) have\nC) will\nD) would','A','B2','hard','tense_usage','general','flight_deck',true,true,1),
('grammar','fill_blank','Complete: The approach was _____ (extreme) challenging due to crosswinds.','extremely','B1','medium','structural_accuracy','general','flight_deck',true,true,1),
('grammar','multiple_choice','Each crew member _____ responsible for checking their own emergency equipment.\nA) is\nB) are\nC) were\nD) been','A','A2','easy','structural_accuracy','general','flight_deck',true,true,1),
('grammar','multiple_choice','The crew reported that they _____ experiencing severe icing at FL280.\nA) are\nB) were\nC) is\nD) has been','B','B1','medium','tense_usage','general','flight_deck',true,true,1),
('grammar','multiple_choice','We should _____ checked the NOTAMs before planning the route.\nA) had\nB) have\nC) has\nD) having','B','B2','medium','structural_accuracy','general','flight_deck',true,true,1),
('grammar','multiple_choice','The aircraft _____ cleared for the ILS approach to Runway 05.\nA) is\nB) was\nC) were\nD) been','B','A2','easy','passive_voice','general','flight_deck',true,true,1),
('grammar','multiple_choice','_____ we receive clearance, we cannot begin our descent.\nA) Until\nB) While\nC) During\nD) Since','A','B1','medium','structural_accuracy','general','flight_deck',true,true,1),

-- Reading (10)
('reading','multiple_choice','Read the ATC clearance:\n\n"Turkish 1923, cleared to Istanbul via ROMEO ONE ALPHA departure, climb and maintain FL180. Squawk 4512. Contact departure on 119.7 after airborne."\n\nWhat altitude should the aircraft climb to initially?\nA) FL120\nB) FL180\nC) FL240\nD) FL350','B','B1','medium','atc_clearance_reading','general','flight_deck',true,true,1),
('reading','multiple_choice','Read the METAR:\n\n"METAR LTFM 181200Z 24018G32KT 6000 TSRA SCT025CB BKN040 22/18 Q1008 TEMPO 2000 +TSRA"\n\nWhat weather phenomenon is occurring?\nA) Snow\nB) Thunderstorm with rain\nC) Fog\nD) Clear skies','B','B2','hard','weather_report_reading','general','flight_deck',true,true,1),
('reading','multiple_choice','Read the performance chart note:\n\n"WARNING: For runways with a slope greater than 2%, add 10% to the calculated takeoff distance. For wet runways, add 15%. These factors are cumulative — apply both corrections when both conditions exist."\n\nA runway has 2.5% slope and is wet. What total correction should be applied?\nA) 10%\nB) 15%\nC) 25%\nD) 20%','C','B2','hard','technical_manual','general','flight_deck',true,true,1),
('reading','multiple_choice','Read the NOTAM:\n\n"NOTAM C0156/26 — Crane operating near RWY 18 threshold, max height 85ft AGL, position 0.3nm south of threshold. Crane lit day and night. No effect on instrument approach minimums."\n\nWhere is the crane located?\nA) On the runway\nB) 0.3nm south of Runway 18 threshold\nC) At the airport terminal\nD) Near the control tower','B','B1','medium','notam_interpretation','general','flight_deck',true,true,1),
('reading','multiple_choice','Read the SID (Standard Instrument Departure) note:\n\n"ROMEO 1A DEPARTURE: After takeoff, climb runway heading to 2000ft, then turn right heading 090 to intercept the ROM R-120. Cross ABCDE at or above FL080. Maximum speed 250kt below FL100."\n\nWhat is the maximum speed below FL100?\nA) 200kt\nB) 250kt\nC) 300kt\nD) No limit','B','B1','medium','sop_comprehension','general','flight_deck',true,true,1),
('reading','multiple_choice','Read the fuel slip:\n\n"Aircraft: TC-FLY | Block Fuel: 18,400 kg | Trip Fuel: 12,200 kg | Contingency: 610 kg | Alternate: 2,800 kg | Final Reserve: 1,200 kg | Taxi: 400 kg | Extra: 1,190 kg"\n\nWhat is the minimum fuel required to reach the alternate airport?\nA) 12,200 kg\nB) 2,800 kg\nC) 18,400 kg\nD) 1,200 kg','B','B2','medium','technical_manual','general','flight_deck',true,true,1),
('reading','multiple_choice','Read the MEL (Minimum Equipment List) entry:\n\n"Item 34-12: Weather Radar — May be inoperative provided: (a) flight is conducted in VMC or where thunderstorms are not forecast, (b) operations are limited to day only, (c) captain accepts responsibility for weather avoidance."\n\nCan the aircraft fly at night without weather radar?\nA) Yes, with captain approval\nB) No, only day operations\nC) Yes, in any conditions\nD) Only if an alternate radar is available','B','B2','hard','technical_manual','general','flight_deck',true,true,1),
('reading','multiple_choice','Read the briefing card:\n\n"ATIS Information Charlie: Runway in use 36L. Wind 350/12kt. Visibility 8000m. Cloud FEW030, BKN060. Temperature 16, dew point 10. QNH 1018. Transition level FL70. Expect ILS approach."\n\nWhat is the QNH setting?\nA) 1008\nB) 1018\nC) 1028\nD) 1038','B','A2','easy','weather_report_reading','general','flight_deck',true,true,1),
('reading','multiple_choice','Read the emergency checklist extract:\n\n"ENGINE FIRE IN FLIGHT:\n1. Affected engine thrust lever — IDLE\n2. Affected engine fire handle — PULL\n3. If fire warning continues after 10 seconds — rotate handle to agent 1\n4. If fire warning continues — rotate handle to agent 2\n5. If fire warning continues — LAND AT NEAREST SUITABLE AIRPORT"\n\nWhat should be done first in an engine fire?\nA) Pull the fire handle\nB) Set the engine thrust to idle\nC) Rotate to agent 1\nD) Land immediately','B','B1','medium','sop_comprehension','general','flight_deck',true,true,1),
('reading','multiple_choice','Read the weight and balance note:\n\n"The aircraft centre of gravity must remain within the forward limit of 18% MAC and aft limit of 33% MAC throughout all phases of flight. Exceeding the aft limit may result in loss of pitch control."\n\nWhat happens if CG exceeds the aft limit?\nA) The aircraft uses less fuel\nB) Possible loss of pitch control\nC) The flight is more comfortable\nD) Nothing significant','B','B2','hard','technical_manual','general','flight_deck',true,true,1),

-- Writing (8)
('writing','written_response','You are a pilot. During cruise at FL370, you encountered unexpected severe turbulence that injured one cabin crew member. Write a brief incident report (at least 60 words) describing the event, actions taken, and the current status.','Model answer should include altitude, time, type of turbulence, injuries, ATC notification, diversion consideration, and crew status.','B2','hard','incident_report','general','flight_deck',true,true,1),
('writing','written_response','Write a message to your airline''s operations department requesting a route change for tomorrow''s flight due to volcanic ash reported along the planned route. Include the flight number, original route, and your proposed alternative (at least 50 words).','Model answer should include formal request, flight details, safety concern, alternative route suggestion.','B1','medium','operational_message','general','flight_deck',true,true,1),
('writing','written_response','You are the captain. Write a short entry in the aircraft technical log describing a cockpit warning light that illuminated during flight but later extinguished. Include what happened, the system affected, and your recommendation (at least 50 words).','Model answer should include specific system, time of occurrence, actions taken, MEL reference if applicable.','B1','medium','maintenance_log','general','flight_deck',true,true,1),
('writing','written_response','A new first officer will be joining your crew next week. Write a welcome email (at least 50 words) introducing yourself, describing what to expect on the first flight together, and offering to answer any questions.','Model answer should be professional yet welcoming, mention briefing procedures, CRM expectations.','A2','easy','operational_message','general','flight_deck',true,true,1),
('writing','written_response','Write a PIREP (Pilot Report) in narrative form (at least 50 words) reporting moderate icing you encountered between FL180 and FL220 during descent into Ankara. Include the type of icing, location, and advice for other pilots.','Model answer should include icing type, altitude range, location, OAT, recommendation.','B2','hard','technical_description','general','flight_deck',true,true,1),
('writing','written_response','You need to report a bird strike that occurred during takeoff. Write a brief report (at least 50 words) for the airline safety department including when, where, which part of the aircraft was struck, and any damage observed.','Model answer should include time, runway, phase of flight, impact location, damage assessment, action taken.','B1','medium','incident_report','general','flight_deck',true,true,1),
('writing','written_response','You are a captain writing feedback about a training flight with a cadet pilot. Describe their strengths and one area for improvement (at least 60 words).','Model answer should be constructive, specific, mention CRM skills, technical ability, and recommendation.','B2','medium','safety_report','general','flight_deck',true,true,1),
('writing','written_response','Write a brief fuel complaint report. Your aircraft consistently burns 8% more fuel than planned on the Istanbul-London route. Describe the issue, provide evidence, and suggest possible causes (at least 60 words).','Model answer should include specific route data, comparison with planned figures, possible causes like weather/weight/routing.','B2','hard','technical_description','general','flight_deck',true,true,1),

-- Speaking (8)
('speaking','audio_response','You are the captain making a passenger announcement. Inform passengers that you are beginning your descent into Istanbul, the weather there is sunny with 22°C, and you will be landing in approximately 25 minutes.\n\nSpeak for at least 30 seconds.','Expected: Professional PA tone, clear weather info, landing time, thank passengers.','A2','easy','cabin_announcement','general','flight_deck',true,true,1),
('speaking','audio_response','Roleplay: You are speaking to ATC. Report that you have a hydraulic system caution light and request priority handling for landing. State your position, altitude, and intentions.\n\nSpeak for at least 30 seconds.','Expected: Proper radio phraseology, callsign, position, nature of problem, request for priority.','B2','hard','roleplay_atc','general','flight_deck',true,true,1),
('speaking','audio_response','Describe what CRM (Crew Resource Management) means to you as a pilot. Why is it important? Give one example from your experience or training.\n\nSpeak for at least 45 seconds.','Expected: Definition of CRM, importance of communication/teamwork, concrete example, professional reflection.','B2','medium','oral_briefing','general','flight_deck',true,true,1),
('speaking','audio_response','You are briefing your first officer before a flight to London. Cover the weather, route, fuel status, and any special considerations for today''s flight.\n\nSpeak for at least 45 seconds.','Expected: Structured briefing, weather summary, route overview, fuel figures, NOTAMs awareness, CRM elements.','B1','medium','crew_coordination','general','flight_deck',true,true,1),
('speaking','audio_response','Explain what you would do if you lost all engine power at FL350. Describe your immediate actions and decision-making process.\n\nSpeak for at least 40 seconds.','Expected: Declare mayday, establish best glide, attempt restart, identify nearest airport, communicate with ATC/cabin crew.','B2','hard','roleplay_emergency','general','flight_deck',true,true,1),
('speaking','audio_response','Roleplay: You are the pilot speaking to a ground engineer on the intercom before departure. There is a discrepancy in the technical log that you want clarified before accepting the aircraft.\n\nSpeak for at least 30 seconds.','Expected: Professional tone, specific reference to log entry, clear question, safety-first attitude.','B1','medium','ground_communication','general','flight_deck',true,true,1),
('speaking','audio_response','Describe the standard approach briefing you would give before an ILS approach to Runway 05 at Antalya. Include the key elements.\n\nSpeak for at least 40 seconds.','Expected: Approach type, runway, frequencies, altitude constraints, go-around procedure, weather minima, threat assessment.','B2','medium','oral_briefing','general','flight_deck',true,true,1),
('speaking','audio_response','You are a training captain. A trainee asks you: "What was the most challenging situation you faced as a pilot?" Share a brief story and what you learned from it.\n\nSpeak for at least 45 seconds.','Expected: Narrative structure, specific situation, actions taken, lesson learned, relevance to safety.','B1','medium','oral_briefing','general','flight_deck',true,true,1),

-- Listening (12)
('listening','multiple_choice','[AUDIO] "Turkish 1923, descend and maintain flight level 180. Report reaching. Traffic 2 o''clock, 10 miles, opposite direction, a Boeing 777 at flight level 190."\n\nWhat altitude should the pilot descend to?\nA) FL190\nB) FL180\nC) FL170\nD) FL200','B','B1','medium','atc_phraseology','general','flight_deck',true,true,1),
('listening','multiple_choice','[AUDIO] "Pegasus 245, wind check: 270 degrees at 18 knots, gusting 28. Cleared to land Runway 27 Left. Caution: braking action reported medium to poor by preceding aircraft."\n\nWhat is the maximum wind gust?\nA) 18 knots\nB) 28 knots\nC) 27 knots\nD) 45 knots','B','B1','medium','atc_phraseology','general','flight_deck',true,true,1),
('listening','multiple_choice','[AUDIO] "All stations, all stations. Istanbul Approach. SIGMET information: severe turbulence reported by multiple aircraft between FL250 and FL350 in the area south of Istanbul. Pilots are advised to avoid this area if possible."\n\nWhat is being reported?\nA) Volcanic ash\nB) Severe turbulence between FL250-FL350\nC) Low visibility\nD) Engine failure','B','B2','medium','emergency_broadcast','general','flight_deck',true,true,1),
('listening','multiple_choice','[AUDIO] "SunExpress 402, hold short of Runway 36 Left. Traffic on final, 3 miles. Expect clearance in approximately 2 minutes. Monitor tower 118.1."\n\nWhat must the pilot do?\nA) Take off immediately\nB) Hold short of Runway 36L and wait\nC) Switch to departure frequency\nD) Cross the runway','B','A2','easy','atc_phraseology','general','flight_deck',true,true,1),
('listening','multiple_choice','[AUDIO] "Mayday, Mayday, Mayday. This is AnadoluJet 891. We have an engine fire, left engine. Currently at FL280, 45 miles southeast of Ankara. Requesting immediate vectors for Ankara Runway 03. Souls on board: 162."\n\nHow many people are on the aircraft?\nA) 89\nB) 162\nC) 280\nD) 45','B','B1','medium','emergency_broadcast','general','flight_deck',true,true,1),
('listening','multiple_choice','[AUDIO] "Turkish 1901, contact Istanbul Control on 132.4. Good day."\n\nWhat frequency should the pilot switch to?\nA) 118.1\nB) 121.5\nC) 132.4\nD) 119.7','C','A2','easy','atc_phraseology','general','flight_deck',true,true,1),
('listening','multiple_choice','[AUDIO] "Cabin crew report: The number 2 lavatory smoke detector activated during cruise. We investigated — a passenger was smoking. The cigarette has been extinguished and the passenger has been warned. No damage to the aircraft."\n\nWhat caused the smoke detector to activate?\nA) An electrical fire\nB) A passenger was smoking\nC) Engine smoke entered the cabin\nD) The detector malfunctioned','B','B1','medium','cockpit_communication','general','flight_deck',true,true,1),
('listening','multiple_choice','[AUDIO] "Flight crew, this is dispatch. Weather update for your destination: Istanbul Airport is now reporting 300 metres visibility in fog. The airport is currently CAT III operations only. Your aircraft is CAT IIIA certified. Confirm you are qualified for CAT III approach."\n\nWhat is the current visibility at Istanbul?\nA) 3000 metres\nB) 300 metres\nC) 30 metres\nD) 3 kilometres','B','B2','hard','cockpit_communication','general','flight_deck',true,true,1),
('listening','multiple_choice','[AUDIO] "Turkish 1923, turn left heading 270 for traffic avoidance. Expect radar vectors back to the ILS Runway 05 approach. Maintain 4000 feet."\n\nWhy must the pilot turn left?\nA) To line up with the runway\nB) To avoid other traffic\nC) Due to wind conditions\nD) For fuel saving','B','B1','medium','atc_phraseology','general','flight_deck',true,true,1),
('listening','multiple_choice','[AUDIO] "Ground, Pegasus 173 at Gate 5, requesting startup and pushback. We have ATIS information Delta. Two-five-zero-zero kilograms of fuel remaining to be loaded."\n\nWhat is the pilot requesting?\nA) Landing clearance\nB) Startup and pushback\nC) Taxi to runway\nD) Parking assignment','B','A2','easy','atc_phraseology','general','flight_deck',true,true,1),
('listening','multiple_choice','[AUDIO] "Attention crew. We will be entering an area of known moderate to severe turbulence in approximately 15 minutes. Cabin service should be completed and secured. Cabin crew take your seats 5 minutes before entry. I will make a PA to passengers shortly."\n\nHow much warning time is given before turbulence?\nA) 5 minutes\nB) 10 minutes\nC) 15 minutes\nD) 20 minutes','C','A2','easy','cockpit_communication','general','flight_deck',true,true,1),
('listening','multiple_choice','[AUDIO] "Turkish 1923, you are number 3 for approach. Reduce speed to 180 knots. Follow the Airbus A321 on a 5-mile final. Report visual with the traffic."\n\nWhat speed should the pilot reduce to?\nA) 150 knots\nB) 160 knots\nC) 180 knots\nD) 200 knots','C','B1','medium','atc_phraseology','general','flight_deck',true,true,1);
